import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";
export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    position: "relative",
  },
  scrollArea: {
    flex: 1,
    alignSelf: "stretch",
  },
  scrollContent: {
    paddingBottom: 120,
    alignItems: "center",
  },
  title: {
    fontSize: 25,
    fontWeight: 900,
    color: colors.headline,
    marginTop: 20,
    marginBottom: 20,
  },
  builtinSection: {
    width: "100%",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  introOverlay: {
    position: "absolute",
    bottom: "30%",
    left: 0,
    right: 0,
    zIndex: 30,
    elevation: 6,
    paddingHorizontal: 4,
    paddingTop: 8,
  },
  groupSection: {
    width: "100%",
  },
  groupHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
    marginBottom: 12,
  },
  groupHeaderLine: {
    flex: 1,
    borderBottomWidth: 4,
    borderStyle: "dashed",
    borderColor: colors.border,
    marginRight: 12,
  },
  groupHeaderBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  groupHeaderLanguage: {
    flexDirection: "row",
    alignItems: "center",
  },
  groupHeaderCode: {
    fontSize: 20,
    fontWeight: 800,
    color: colors.headline,
    marginRight: 6,
  },
  groupHeaderSeparator: {
    marginHorizontal: 8,
    fontSize: 20,
    fontWeight: 800,
    color: colors.headline,
  },
  groupHeaderFlag: {
    width: 99 / 3,
    height: 66 / 3,
    borderRadius: 5,
  },
  groupCourses: {
    marginTop: 12,
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  minicontainer: {
    width: "75%",
  },
  courseCard: {
    width: "100%",
    height: 92,
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    backgroundColor: colors.secondBackground,
    borderRadius: 15,
    paddingLeft: "10%",
    paddingRight: "10%",
    position: "relative",
  },
  courseCardText: {
    fontSize: 25,
    fontWeight: 900,
    color: colors.headline,
    flex: 1,
    textAlign: "left",
    marginLeft: 12,
  },
  customSection: {
    width: "100%",
    marginTop: 24,
    gap: 12,
  },
  customSectionTitle: {
    fontSize: 25,
    fontWeight: 900,
    color: colors.headline,
  },
  groupSubtitle: {
    fontSize: 18,
    fontWeight: 700,
    color: colors.headline,
  },
  customList: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  customEmptyText: {
    color: colors.paragraph,
    fontStyle: "italic",
  },
  customCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 15,
    paddingLeft: "7%",
    paddingRight: "7%",
    backgroundColor: colors.secondBackground,
    height: 92,
    
  },
  customCardContent: {
    flex: 1,
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
        // gap: 2,
  },
  customIconBadge: {
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  customIconFlag: {
    position: "absolute",
    bottom: -3,
    right: -3,
    width: 99 / 3,
    height: 66 / 3,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  customCardInfo: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
    alignItems: "flex-start",
  },
  customCardTitleContainer: {
    width: "100%",
    overflow: "hidden",
  },
  customCardTitle: {
    fontSize: 25,
    fontWeight: 900,
    color: colors.headline,
  },
  customCardMeta: {
    fontSize: 12,
    fontWeight: 900,
    color: colors.headline,
  },
  customEditButton: {
    padding: 4,
    marginLeft: 8,
    // backgroundColor: colors.my_yellow,
    alignItems: "center",
    justifyContent: "center",
  },
  courseEditButton: {
    padding: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyContainer: {
    width: "100%",
    minHeight: 240,
    alignItems: "center",
    justifyContent: "center",
  },
  emptyState: {
    fontSize: 26,
    fontWeight: 800,
    textAlign: "center",
    color: colors.paragraph,
  },
  buttonscontainer: {
    width: "100%",
    paddingBottom: 24,
    gap: 12,
    backgroundColor: colors.background,
    alignItems: "center",
  },
  buttonsRow: {
    borderColor: colors.border,
    borderTopWidth: 3,
    paddingTop: 15,
    width: "75%",
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  nextButton: {
    width: 90,
    height: 50,
    borderRadius: 12,
    backgroundColor: colors.my_green,
    alignItems: "center",
    justifyContent: "center",
  },
  nextButtonDisabled: {
    backgroundColor: colors.border,
  },
  nextButtonLabel: {
    fontSize: 16,
    fontWeight: "900",
    textTransform: "uppercase",
    color: colors.headline,
  },
  nextButtonLabelDisabled: {
    color: colors.paragraph,
    opacity: 0.6,
  },
  flag: {
    width: 99 / 1.25,
    height: 66 / 1.25,
    // backgroundColor: colors.my_green,
  },
  clicked: {
    backgroundColor: colors.my_green,
  },
}));
