import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    // justifyContent: "center",
    // alignItems: "center",
    backgroundColor: colors.background,
    // marginTop: 20,
    paddingTop: 15,
    position: "relative",
    display: "flex",
  },
  loadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: colors.background,
    zIndex: 40,
  },
  loadingOverlayContent: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  content: {
    flex: 1,
  },
  cardSectionWrapper: {
    marginBottom: 10,
  },
  topButtonsWrapper: {
    marginBottom: 10,
  },
  topActionsWrapper: {
    paddingHorizontal: 16,
    alignItems: "center",
  },
  boxesWrapper: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    position: "relative",
    alignItems: "center",
    paddingHorizontal: 12,
    marginTop: 0,
  },
  boxesWrapperWithBottomButtons: {
    marginTop: 8,
  },
  boxesViewport: {
    flex: 1,
    minHeight: 0,
    width: "100%",
    alignItems: "center",
  },
  boxesViewportScrollContent: {
    width: "100%",
    alignItems: "center",
  },
  boxesScaledContent: {
    width: "100%",
    alignItems: "center",
  },
  bottomButtonsWrapper: {
    marginTop: 4,
    marginBottom: 2,
  },
  bottomButtonsDock: {
    position: "absolute",
    left: 0,
    right: 0,
    zIndex: 10,
  },
  addButton: {
    position: "absolute",
    top: -6,
    right: 42,
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: colors.my_yellow,
    justifyContent: "center",
    alignItems: "center",
    shadowRadius: 1.4,
    zIndex: 1000,
  },
  introOverlay: {
    position: "absolute",
    bottom: "30%",
    left: 0,
    right: 0,
    zIndex: 30,
    elevation: 6,
    paddingHorizontal: 4,
    paddingTop: 8,
  },
  actionsPositionNudgeBackdrop: {
    flex: 1,
    backgroundColor: "#00000055",
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  actionsPositionNudgeCard: {
    backgroundColor: colors.background,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 16,
    paddingTop: 18,
    paddingBottom: 14,
  },
  actionsPositionNudgeTitle: {
    fontSize: 22,
    fontWeight: "900",
    color: colors.headline,
    textAlign: "center",
  },
  actionsPositionNudgeSubtitle: {
    marginTop: 8,
    marginBottom: 16,
    fontSize: 14,
    lineHeight: 20,
    color: colors.paragraph,
    opacity: 0.84,
    textAlign: "center",
  },
  actionsPositionNudgeOptions: {
    flexDirection: "row",
    columnGap: 12,
  },
  actionsPositionNudgeOption: {
    flex: 1,
    borderRadius: 18,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    alignItems: "center",
  },
  actionsPositionNudgeOptionActive: {
    borderColor: colors.my_green,
  },
  actionsPositionNudgePreviewWrapper: {
    width: "100%",
    aspectRatio: 0.84,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  actionsPositionNudgePreview: {
    width: "100%",
    height: "100%",
    transform: [{ scale: 2.7 }, { translateY: 11 }],
  },
  actionsPositionNudgeOptionLabel: {
    width: "100%",
    borderTopWidth: 1,
    borderColor: colors.border,
    paddingTop: 10,
    paddingBottom: 12,
    fontSize: 16,
    fontWeight: "800",
    color: colors.headline,
    textAlign: "center",
  },
  actionsPositionNudgeDismiss: {
    alignSelf: "center",
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 4,
  },
  actionsPositionNudgeDismissText: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.paragraph,
    opacity: 0.8,
  },
}));
