import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: 18,
    paddingTop: 32,
    paddingBottom: 0,
  },
  section: {
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: 16,
    paddingTop: 32,
  },
  sectionWithManualToolbar: {
    paddingBottom: 164,
  },
  sectionHeader: {
    fontSize: 24,
    textTransform: "uppercase",
    position: "absolute" as const,
    fontWeight: "900",
    right: 24,
    top: 24,
    color: colors.headline,
  },
  addModeTabs: {
    marginTop: 28,
    width: "100%",
  },
  modeContainer: {
    marginTop: 12,
  },
  modeTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.headline,
  },
  modeDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.paragraph,
    marginBottom: 16,
  },
  modeActions: {
    gap: 12,
    alignSelf: "flex-end" as const,
  },
  csvSelectedFile: {
    fontSize: 13,
    fontStyle: "italic",
    color: colors.paragraph,
  },
  miniSectionHeader: {
    fontSize: 16,
    textTransform: "uppercase",
    fontWeight: "900",
    color: colors.headline,
  },
  csvPreviewCard: {
    marginTop: 14,
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    gap: 12,
  },
  csvPreviewTitle: {
    fontSize: 14,
    fontWeight: "900",
    textTransform: "uppercase" as const,
    color: colors.headline,
  },
  csvStatsGrid: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 8,
  },
  csvStatBox: {
    minWidth: "47%",
    flex: 1,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    paddingVertical: 8,
    paddingHorizontal: 10,
    gap: 2,
  },
  csvStatLabel: {
    fontSize: 11,
    textTransform: "uppercase" as const,
    fontWeight: "800",
    color: colors.paragraph,
  },
  csvStatValue: {
    fontSize: 18,
    fontWeight: "900",
    color: colors.headline,
  },
  csvTypeStatsRow: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 8,
  },
  csvTypePill: {
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    backgroundColor: colors.secondBackground,
    color: colors.headline,
    fontSize: 12,
    fontWeight: "700",
  },
  csvIssuesBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 10,
    backgroundColor: colors.secondBackground,
    padding: 10,
    gap: 4,
  },
  csvIssueText: {
    fontSize: 12,
    lineHeight: 17,
    color: colors.headline,
  },
  csvIssueTextMuted: {
    marginTop: 2,
    fontSize: 12,
    color: colors.paragraph,
    fontStyle: "italic" as const,
  },
  csvActionRow: {
    marginTop: 2,
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 10,
    justifyContent: "flex-end" as const,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginHorizontal: 24,
  },
  manualToolbarWrap: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 10,
    backgroundColor: colors.background,
  },
  manualToolbar: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
  },
  manualTypeSelector: {
    flex: 1,
  },
  manualAddButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: colors.my_yellow,
    borderWidth: 1,
    borderColor: colors.border,
  },
  manualAddIcon: {
    fontSize: 28,
    lineHeight: 28,
    fontWeight: "900" as const,
    color: colors.headline,
  },
  footer: {
    width: "100%",
    paddingBottom: 24,
    backgroundColor: colors.background,
    alignItems: "center" as const,
  },
  buttonsRow: {
    borderColor: colors.border,
    borderTopWidth: 3,
    paddingTop: 15,
    width: "100%",
    flexDirection: "row" as const,
    justifyContent: "flex-end" as const,
    gap: 10,
  },
  returnbtn: {
    color: colors.headline,
  },
}));
