import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: 24,
    gap: 24,
  },
  section: {
    backgroundColor: colors.secondBackground,
    borderRadius: 16,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 16,
  },
  sectionHeader: {
    fontSize: 20,
    fontWeight: "700",
    color: colors.headline,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 16,
    color: colors.headline,
    backgroundColor: colors.lightbg,
  },
  iconGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  iconTile: {
    width: 90,
    height: 90,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.lightbg,
    borderWidth: 2,
    borderColor: "transparent",
    gap: 8,
  },
  iconTileSelected: {
    borderColor: colors.my_green,
  },
  iconSquare: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 2,
  },
  iconLabel: {
    marginTop: 6,
    fontSize: 12,
    color: colors.paragraph,
    textAlign: "center",
  },
  segmentedControl: {
    flexDirection: "row",
    backgroundColor: colors.lightbg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  segmentOption: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  segmentOptionLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.paragraph,
  },
  segmentOptionActive: {
    backgroundColor: colors.my_green,
  },
  segmentOptionLabelActive: {
    color: colors.darkbg,
  },
  csvInstruction: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.paragraph,
  },
  csvFileName: {
    fontSize: 14,
    fontStyle: "italic",
    color: colors.headline,
  },
  csvButtons: {
    flexDirection: "row",
    gap: 12,
    flexWrap: "wrap",
  },
  table: {
    gap: 12,
  },
  tableHeader: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 8,
  },
  headerCell: {
    flex: 1,
    fontSize: 14,
    fontWeight: "700",
    color: colors.paragraph,
    paddingLeft: 10,
  },
  headerCellSmall: {
    width: 52,
    fontSize: 14,
    fontWeight: "700",
    color: colors.paragraph,
    textAlign: "center",
  },
  tableBody: {
    gap: 12,
  },
  tableRow: {
    flexDirection: "row",
    gap: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: 8,
    alignItems: "center",
    backgroundColor: colors.lightbg,
  },
  tableCell: {
    flex: 1,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    overflow: "hidden",
  },
  cellInput: {
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 14,
    lineHeight: 20,
    color: colors.headline,
    minHeight: 40,
    textAlignVertical: "top",
  },
  removeButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.my_red,
    alignItems: "center",
    justifyContent: "center",
  },
  removeButtonText: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.lightbg,
    lineHeight: 18,
  },
  removeButtonDisabled: {
    opacity: 0.4,
  },
  addCardButton: {
    alignSelf: "flex-start",
  },
  footer: {
    paddingHorizontal: 24,
    paddingBottom: 32,
    paddingTop: 8,
    gap: 12,
    alignItems: "flex-end",
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginHorizontal: 24,
  },
}));
