import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: 24,
    gap: 24,
    minHeight: "100%",
  },
  section: {
    backgroundColor: colors.secondBackground,
    borderRadius: 16,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
    // gap: 16,
    // paddingTop: 36,
  },
  sectionHeader: {
    fontSize: 30,
    textTransform: "uppercase",
    // position: "absolute",
    width: "100%",
    textAlign: "right",
    fontWeight: "900",
    color: colors.headline,
    margin: 0,
    padding: 0,
    // backgroundColor: colors.my_green,
  },
  miniSectionHeader: {
    fontSize: 20,
    textTransform: "uppercase",
    fontWeight: "900",
    // backgroundColor: colors.my_green,
    color: colors.headline,
  },
  imageContainer: {
    marginBottom: 12,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
    justifyContent: "flex-start",
  },
  iconWrapper: {
    // backgroundColor: colors.my_green,
    flexBasis: "20%",
    // width: "16.6667%",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
    padding: 8,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "transparent",
  },
  iconWrapperSelected: {
    borderColor: colors.my_green,
  },
  iconContainer: {
    // gap: 8,
  },
  colorsContainer: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
    height: "100%",
    justifyContent: "center",

    // Usuń wysokość, aby kontener sam dopasował się do zawartości
  },
  profileColor: {
    width: "16%",
    aspectRatio: 1,
    height: 20,
  },
  profileColorSelected: {
    borderWidth: 3,
    borderColor: colors.my_green,
  },
  profileInput: {
    borderColor: colors.my_yellow,
    borderWidth: 3,
    borderRadius: 8,
    marginBottom: 8,
  },
  segmentedControl: {
    marginTop: 8,
    flexDirection: "row",
    backgroundColor: colors.lightbg,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "hidden",
  },
  segmentOption: {
    flex: 1,
    paddingVertical: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  segmentOptionLabel: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.paragraph,
  },
  segmentOptionActive: {
    backgroundColor: colors.my_green,
  },
  segmentOptionLabelActive: {
    color: colors.darkbg,
  },
  modeContainer: {
    marginTop: 24,
  },
  modeTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.headline,
  },
  modeDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.paragraph,
    marginBottom: 16,
  },
  modeActions: {
    gap: 12,
    alignSelf: "flex-end",
  },
  csvSelectedFile: {
    fontSize: 13,
    fontStyle: "italic",
    color: colors.paragraph,
  },
  manualHeader: {
    flexDirection: "row",
    alignItems: "center",
    // backgroundColor: colors.my_green,
  },
  manualHeaderCell: {
    flex: 1,
    fontSize: 15,
    fontWeight: "700",
    textAlign: "center",
    color: colors.paragraph,
    textTransform: "uppercase",
  },
  manualHeaderSpacer: {
    width: 44,
  },
  manualTable: {
    marginTop: 4,
    // borderRadius: 18,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    overflow: "hidden",
    borderRightWidth: 0,
    borderLeftWidth: 0,
  },
  manualRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  manualRowLast: {
    borderBottomWidth: 0,
  },
  manualCell: {
    flex: 1,
  },
  manualDivider: {
    width: 1,
    alignSelf: "stretch",
    backgroundColor: colors.border,
    marginHorizontal: 12,
  },
  manualInput: {
    paddingHorizontal: 4,
    paddingVertical: 0,
    fontSize: 14,
    lineHeight: 20,
    color: colors.headline,
    textAlignVertical: "top",
    minHeight: 24,
  },
  manualRemoveButton: {
    width: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  manualRemoveButtonDisabled: {
    opacity: 0.3,
  },
  manualRemoveIcon: {
    color: colors.my_red,
    fontSize: 24,
    fontWeight: "900",
    lineHeight: 24,
  },
  manualAddButton: {
    alignSelf: "flex-end",
    backgroundColor: colors.my_yellow,
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 16,
  },
  manualAddIcon: {
    color: colors.headline,
    fontSize: 30,
    fontWeight: "900",
    lineHeight: 30,
  },
  footer: {
    paddingHorizontal: 24,
    paddingBottom: 32,
    paddingTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  footerActionRight: {
    marginLeft: "auto",
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginHorizontal: 24,
  },
}));
