import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useEditStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    padding: 18,
    minHeight: "100%",
    paddingTop: 32,
  },
  section: {
    backgroundColor: colors.secondBackground,
    borderRadius: 16,
    padding: 16,
    paddingTop: 32,
  },
  sectionHeader: {
    fontSize: 24,
    textTransform: "uppercase",
    position: "absolute",
    fontWeight: "900",
    right: 24,
    top: 10,
    color: colors.headline,
  },
  miniSectionHeader: {
    fontSize: 16,
    textTransform: "uppercase",
    fontWeight: "900",
    color: colors.headline,
    marginTop: 8,
  },
  iconContainer: {
    // gap: 8,
  },
  imageContainer: {
    marginBottom: 12,
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
    justifyContent: "flex-start",
  },
  iconWrapper: {
    flexBasis: "20%",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 6,
    padding: 8,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "transparent",
  },
  iconWrapperSelected: {
    borderColor: colors.my_green,
  },
  colorsContainer: {
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    width: "100%",
    justifyContent: "center",
  },
  profileColor: {
    width: "16%",
    aspectRatio: 1,
    height: 20,
  },
  profileColorSelected: {
    borderWidth: 3,
    borderColor: colors.my_green,
  },
  profileInput: {
    borderColor: colors.my_yellow,
    borderWidth: 3,
    borderRadius: 8,
    paddingLeft: 8,
    fontSize: 16,
  },
  card: {
    flexDirection: "row",
    width: "100%",
    borderBottomWidth: 2,
    borderColor: colors.border,
    alignItems: "flex-start",
    paddingVertical: 12,
  },
  cardFirst: {
    borderTopWidth: 2,
  },
  number: {
    fontSize: 16,
    fontWeight: 900,
    width: "10%",
    height: "100%",
    maxHeight:"100%",
    minWidth: 36,
    textAlign: "center",
    textAlignVertical: "center",
    paddingTop: 6,
    // backgroundColor: 'red',
  },
  inputContainer: {
    flex: 1,
    gap: 12,
  },
  cardinput: {
    width: "100%",
    fontSize: 16,
    fontWeight: 800,
    paddingVertical: 6,
  },
  cardPlaceholder: {
    color: colors.border,
  },
  cardDivider: {
    borderStyle: "dashed",
    borderTopWidth: 2,
    borderColor: colors.border,
    alignSelf: "stretch",
  },
  answersContainer: {
    gap: 12,
  },
  answerRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  answerIndex: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.headline,
    width: 24,
    textAlign: "right",
  },
  answerInput: {
    flex: 1,
    fontSize: 16,
    fontWeight: 700,
    paddingVertical: 6,
  },
  answerRemoveButton: {
    padding: 4,
  },
  cardActions: {
    width: 48,
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    gap: 12,
  },
  cardActionButton: {
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
  },
  cardActionIcon: {
    color: colors.headline,
  },
  removeButtonDisabled: {
    opacity: 0.4,
  },
  manualAddButton: {
    alignSelf: "flex-end",
    backgroundColor: colors.my_yellow,
    width: 56,
    height: 56,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 16,
  },
  manualAddIcon: {
    color: colors.headline,
    fontSize: 30,
    fontWeight: "900",
    lineHeight: 30,
  },
  buttonContainer: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  footer: {
    paddingHorizontal: 24,
    paddingBottom: 32,
    paddingTop: 8,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
}));
