import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 56,
  },
  section: {
    backgroundColor: colors.secondBackground,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#00000011",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  header: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.paragraph,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: colors.paragraph,
    opacity: 0.9,
    marginBottom: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    columnGap: 12,
  },
  buttonWrapper: {
    flexDirection: "row",
    justifyContent: "flex-start",
    columnGap: 12,
    marginTop: 8,
  },
  status: {
    marginTop: 10,
    fontSize: 13,
    color: colors.paragraph,
    opacity: 0.85,
  },

  // Panel (diagnostics)
  panel: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    borderRadius: 22,
    marginBottom: 16,
    shadowColor: "#00000011",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
    overflow: "hidden",
  },
  panelHeader: {
    paddingHorizontal: 16,
    paddingVertical: 14,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    backgroundColor: colors.secondBackground,
  },
  panelTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.headline,
  },
  panelSubtitle: {
    fontSize: 13,
    color: colors.paragraph,
    opacity: 0.75,
    marginTop: 4,
  },
  switchPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  switchLabel: {
    fontSize: 12,
    color: colors.paragraph,
  },
  panelBody: {
    paddingHorizontal: 16,
    paddingVertical: 16,
    gap: 10,
  },
  sectionTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  sectionName: {
    fontWeight: "700",
    fontSize: 14,
    color: colors.headline,
  },
  sectionHint: {
    fontSize: 12,
    color: colors.paragraph,
    opacity: 0.8,
    marginTop: 4,
  },
  chips: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
    paddingVertical: 2,
  },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  chipDisabled: {
    opacity: 0.5,
  },
  chipBox: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  chipCheck: {
    width: 10,
    height: 10,
    borderRadius: 3,
    backgroundColor: colors.my_green,
  },
  chipText: {
    fontSize: 13,
    color: colors.headline,
    letterSpacing: 0.1,
  },
  chipUnchecked: {
    backgroundColor: colors.secondBackground,
  },
  chipChecked: {
    backgroundColor: colors.background,
    borderColor: colors.my_green,
  },
  footer: {
    marginTop: 6,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
    borderRadius: 16,
    backgroundColor: colors.background,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  footerLeft: {
    flex: 1,
    gap: 4,
  },
  footerTitle: {
    fontSize: 12,
    color: colors.paragraph,
    opacity: 0.75,
  },
  footerSummary: {
    fontSize: 13,
    color: colors.headline,
  },
  footerButton: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    backgroundColor: colors.secondBackground,
  },
  footerButtonText: {
    fontSize: 12,
    color: colors.headline,
    fontWeight: "700",
  },
}));
