import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  minicontainer: {
    width: "75%",
    height: "90%",
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    // justifyContent: "space-between",
    // backgroundColor: colors.my_red,
  },
  tile: {
    marginTop: 30,
    alignItems: "center",
    justifyContent: "center",
    width: "50%",
    // backgroundColor: colors.my_red,
  },
  level: {
    fontSize: 80,
    color: colors.headline,
    fontWeight: 900,
  },
  progressTrack: {
    backgroundColor: colors.my_red,
    height: 18,
    width: "80%",
    // borderRadius: 4,
    // marginTop: 8,
    overflow: "hidden",
  },
  hiddenProgressTrack: {
    opacity: 0,
  },
  progressFill: {
    backgroundColor: colors.my_green,
    height: "100%",
    // borderRadius: 4,
  },
  choose: {
    marginTop: 10,
    width: "100%",
    fontSize: 25,
    color: colors.headline,
    textAlign: "center",
    fontWeight: 800,
    textTransform: "uppercase",
  },

  reviewTile: {
    // marginTop: "2%",
    width: 145,
    height: 155,
    aspectRatio: 1,
    paddingTop: 22,
    alignItems: "center",
    justifyContent: "center",
    padding: 0,
    borderWidth: 2,
    borderRadius: 10,
    borderColor: colors.border,
    margin: 5,
    // backgroundColor: colors.my_red,
  },
  reviewLevel: {
    fontSize: 70,
    color: colors.headline,
    fontWeight: 900,
    padding: 0,
    margin: 0,
    lineHeight: 60,
    textAlign: "center",
    // includeFontPadding: false,
  },
  number: {
    padding: 0,
    margin: 0,
    fontSize: 30,
    lineHeight: 30,
    textAlign: "right",
    // includeFontPadding: false,
    color: colors.my_red,
    fontWeight: 900,
    paddingRight: 2,
    // backgroundColor: colors.my_green
  },
  test: {
    // backgroundColor: colors.my_green
  },
  reviewMinicontainer: {
    width: "80%",
    height: "90%",
    display: "flex",
    flexDirection: "row",
    flexWrap: "wrap",
    // justifyContent: "space-between",
    // backgroundColor: colors.my_red,
  },
}));
