import type { BoxesState } from "@/src/types/boxes";

export type CoachmarkAdvanceEvent =
  | "manual"
  | "pin_course"
  | "activate_course"
  | "open_review_course"
  | "press_next"
  | "box_selected"
  | "answer_submitted"
  | "forced_correct_answer_shown"
  | "box_promoted"
  | "confetti_demo_shown";

export type CoachmarkFlowStep = {
  id: string;
  targetId: string;
  titleKey: string;
  descriptionKey: string;
  kind: "info" | "action" | "success";
  advanceOn: CoachmarkAdvanceEvent;
  spotlight?: boolean;
  blockOutside?: boolean;
  blockSpotlight?: boolean;
  layout?: "default" | "centered_intro";
  scrollLocked?: boolean;
  expectedBox?: keyof BoxesState;
  forceCorrectOnSubmit?: boolean;
  dismissKeyboardOnAdvance?: boolean;
  showDemoBoxCounts?: Partial<Record<keyof BoxesState, number>>;
  triggerDemoConfetti?: boolean;
  successVariant?: "normal" | "assisted";
  autoAdvanceDelayMs?: number;
  floatingIndicator?: "arrow_u_down_right";
  avoidTargetIds?: string[];
};

export const COURSE_PIN_COACHMARK_STEPS: CoachmarkFlowStep[] = [
  {
    id: "course-pin-step-1",
    targetId: "course-pin-bubble-anchor",
    titleKey: "onboarding.coursePin.step1.title",
    descriptionKey: "onboarding.coursePin.step1.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    layout: "centered_intro",
    scrollLocked: true,
  },
  {
    id: "course-pin-step-2",
    targetId: "course-pin-bubble-anchor",
    titleKey: "onboarding.coursePin.step2.title",
    descriptionKey: "onboarding.coursePin.step2.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
  {
    id: "course-pin-step-3",
    targetId: "course-pin-first-card",
    titleKey: "onboarding.coursePin.step3.title",
    descriptionKey: "onboarding.coursePin.step3.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
    scrollLocked: true,
  },
  {
    id: "course-pin-step-4",
    targetId: "course-pin-bubble-anchor",
    titleKey: "onboarding.coursePin.step4.title",
    descriptionKey: "onboarding.coursePin.step4.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
  {
    id: "course-pin-step-5",
    targetId: "course-pin-first-pin-button",
    titleKey: "onboarding.coursePin.step5.title",
    descriptionKey: "onboarding.coursePin.step5.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
    scrollLocked: true,
  },
  {
    id: "course-pin-step-6",
    targetId: "course-pin-tab-switcher",
    titleKey: "onboarding.coursePin.step6.title",
    descriptionKey: "onboarding.coursePin.step6.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
    scrollLocked: true,
  },
  {
    id: "course-pin-step-7",
    targetId: "course-pin-bubble-anchor",
    titleKey: "onboarding.coursePin.step7.title",
    descriptionKey: "onboarding.coursePin.step7.description",
    kind: "info",
    advanceOn: "pin_course",
  },
  {
    id: "course-pin-step-8",
    targetId: "course-pin-bubble-anchor",
    titleKey: "onboarding.coursePin.step8.title",
    descriptionKey: "onboarding.coursePin.step8.description",
    kind: "success",
    advanceOn: "manual",
    blockOutside: true,
  },
  {
    id: "course-pin-step-9",
    targetId: "course-pin-next-button",
    titleKey: "onboarding.coursePin.step9.title",
    descriptionKey: "onboarding.coursePin.step9.description",
    kind: "action",
    advanceOn: "press_next",
    spotlight: true,
    scrollLocked: true,
  },
];

export const COURSE_ACTIVATE_COACHMARK_STEPS: CoachmarkFlowStep[] = [
  {
    id: "course-activate-step-1",
    targetId: "course-activate-bubble-anchor",
    titleKey: "onboarding.courseActivate.step1.title",
    descriptionKey: "onboarding.courseActivate.step1.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
  },
  {
    id: "course-activate-step-2",
    targetId: "course-activate-bubble-anchor",
    titleKey: "onboarding.courseActivate.step2.title",
    descriptionKey: "onboarding.courseActivate.step2.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
  },
  {
    id: "course-activate-step-3",
    targetId: "course-activate-first-card",
    titleKey: "onboarding.courseActivate.step3.title",
    descriptionKey: "onboarding.courseActivate.step3.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
  },
  {
    id: "course-activate-step-4",
    targetId: "course-activate-bubble-anchor",
    titleKey: "onboarding.courseActivate.step4.title",
    descriptionKey: "onboarding.courseActivate.step4.description",
    kind: "action",
    advanceOn: "activate_course",
  },
  {
    id: "course-activate-step-5",
    targetId: "course-activate-next-button",
    titleKey: "onboarding.courseActivate.step5.title",
    descriptionKey: "onboarding.courseActivate.step5.description",
    kind: "action",
    advanceOn: "press_next",
    spotlight: true,
  },
];

export const COURSE_ENTRY_SETTINGS_COACHMARK_STEPS: CoachmarkFlowStep[] = [
  {
    id: "course-entry-settings-step-1",
    targetId: "course-entry-settings-bubble-anchor",
    titleKey: "onboarding.courseEntrySettings.step1.title",
    descriptionKey: "onboarding.courseEntrySettings.step1.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
  {
    id: "course-entry-settings-step-2",
    targetId: "course-entry-settings-options",
    titleKey: "onboarding.courseEntrySettings.step2.title",
    descriptionKey: "onboarding.courseEntrySettings.step2.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
    scrollLocked: true,
  },
  {
    id: "course-entry-settings-step-3",
    targetId: "course-entry-settings-bubble-anchor",
    titleKey: "onboarding.courseEntrySettings.step3.title",
    descriptionKey: "onboarding.courseEntrySettings.step3.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
  },
  {
    id: "course-entry-settings-step-4",
    targetId: "course-entry-settings-bubble-anchor",
    titleKey: "onboarding.courseEntrySettings.step4.title",
    descriptionKey: "onboarding.courseEntrySettings.step4.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
  {
    id: "course-entry-settings-step-5",
    targetId: "course-entry-settings-next-button",
    titleKey: "onboarding.courseEntrySettings.step5.title",
    descriptionKey: "onboarding.courseEntrySettings.step5.description",
    kind: "action",
    advanceOn: "press_next",
    spotlight: true,
    scrollLocked: true,
  },
];

export const REVIEW_COURSES_COACHMARK_STEPS: CoachmarkFlowStep[] = [
  {
    id: "review-courses-step-1",
    targetId: "review-courses-bubble-anchor",
    titleKey: "onboarding.reviewCourses.step1.title",
    descriptionKey: "onboarding.reviewCourses.step1.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    layout: "centered_intro",
    scrollLocked: true,
  },
  {
    id: "review-courses-step-2",
    targetId: "flashcards-review-button",
    titleKey: "onboarding.reviewCourses.step2.title",
    descriptionKey: "onboarding.reviewCourses.step2.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
  },
  {
    id: "review-courses-step-3",
    targetId: "flashcards-review-button",
    titleKey: "onboarding.reviewCourses.step3.title",
    descriptionKey: "onboarding.reviewCourses.step3.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
  },
  {
    id: "review-courses-step-4",
    targetId: "review-courses-first-card",
    titleKey: "onboarding.reviewCourses.step4.title",
    descriptionKey: "onboarding.reviewCourses.step4.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
    scrollLocked: true,
  },
  {
    id: "review-courses-step-5",
    targetId: "review-courses-first-card-badge",
    titleKey: "onboarding.reviewCourses.step5.title",
    descriptionKey: "onboarding.reviewCourses.step5.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
    scrollLocked: true,
  },
  {
    id: "review-courses-step-6",
    targetId: "review-courses-first-card",
    titleKey: "onboarding.reviewCourses.step6.title",
    descriptionKey: "onboarding.reviewCourses.step6.description",
    kind: "action",
    advanceOn: "open_review_course",
    spotlight: true,
    blockOutside: true,
    scrollLocked: true,
  },
];

const REVIEW_FLASHCARDS_ACTION_BUTTON_AVOID_TARGET_IDS = [
  "review-flashcards-add-button",
  "review-flashcards-confirm-button",
];

const REVIEW_FLASHCARDS_COACHMARK_BASE_STEPS: CoachmarkFlowStep[] = [
  {
    id: "review-flashcards-step-1",
    targetId: "review-flashcards-bubble-anchor",
    titleKey: "onboarding.reviewFlashcards.step1.title",
    descriptionKey: "onboarding.reviewFlashcards.step1.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
  {
    id: "review-flashcards-step-2",
    targetId: "review-flashcards-bubble-anchor",
    titleKey: "onboarding.reviewFlashcards.step2.title",
    descriptionKey: "onboarding.reviewFlashcards.step2.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
  {
    id: "review-flashcards-step-3",
    targetId: "review-flashcards-box-counts",
    titleKey: "onboarding.reviewFlashcards.step3.title",
    descriptionKey: "onboarding.reviewFlashcards.step3.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
    scrollLocked: true,
  },
  {
    id: "review-flashcards-step-4",
    targetId: "review-flashcards-add-button",
    titleKey: "onboarding.reviewFlashcards.step4.title",
    descriptionKey: "onboarding.reviewFlashcards.step4.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
    scrollLocked: true,
  },
  {
    id: "review-flashcards-step-5",
    targetId: "review-flashcards-boxes-section",
    titleKey: "onboarding.reviewFlashcards.step5.title",
    descriptionKey: "onboarding.reviewFlashcards.step5.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
    scrollLocked: true,
  },
  {
    id: "review-flashcards-step-6",
    targetId: "review-flashcards-bubble-anchor",
    titleKey: "onboarding.reviewFlashcards.step6.title",
    descriptionKey: "onboarding.reviewFlashcards.step6.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
  {
    id: "review-flashcards-step-7",
    targetId: "review-flashcards-bubble-anchor",
    titleKey: "onboarding.reviewFlashcards.step7.title",
    descriptionKey: "onboarding.reviewFlashcards.step7.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
  {
    id: "review-flashcards-step-8",
    targetId: "review-flashcards-bubble-anchor",
    titleKey: "onboarding.reviewFlashcards.step8.title",
    descriptionKey: "onboarding.reviewFlashcards.step8.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
  {
    id: "review-flashcards-step-9",
    targetId: "review-flashcards-bubble-anchor",
    titleKey: "onboarding.reviewFlashcards.step9.title",
    descriptionKey: "onboarding.reviewFlashcards.step9.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
  {
    id: "review-flashcards-step-10",
    targetId: "review-flashcards-bubble-anchor",
    titleKey: "onboarding.reviewFlashcards.step10.title",
    descriptionKey: "onboarding.reviewFlashcards.step10.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    scrollLocked: true,
  },
];

export const REVIEW_FLASHCARDS_COACHMARK_STEPS: CoachmarkFlowStep[] =
  REVIEW_FLASHCARDS_COACHMARK_BASE_STEPS.map((step) => ({
    ...step,
    avoidTargetIds: REVIEW_FLASHCARDS_ACTION_BUTTON_AVOID_TARGET_IDS,
  }));

const FLASHCARDS_ACTION_BUTTON_AVOID_TARGET_IDS = [
  "flashcards-add-button",
  "flashcards-confirm-button",
];

const FLASHCARDS_COACHMARK_BASE_STEPS: CoachmarkFlowStep[] = [
  {
    id: "flashcards-step-1",
    targetId: "flashcards-bubble-anchor",
    titleKey: "onboarding.flashcards.step1.title",
    descriptionKey: "onboarding.flashcards.step1.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
  },
  {
    id: "flashcards-step-2",
    targetId: "flashcards-bubble-anchor",
    titleKey: "onboarding.flashcards.step2.title",
    descriptionKey: "onboarding.flashcards.step2.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
  },
  {
    id: "flashcards-step-3",
    targetId: "flashcards-card-section",
    titleKey: "onboarding.flashcards.step3.title",
    descriptionKey: "onboarding.flashcards.step3.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-4",
    targetId: "flashcards-buttons-section",
    titleKey: "onboarding.flashcards.step4.title",
    descriptionKey: "onboarding.flashcards.step4.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-5",
    targetId: "flashcards-boxes-section",
    titleKey: "onboarding.flashcards.step5.title",
    descriptionKey: "onboarding.flashcards.step5.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-6",
    targetId: "flashcards-box-one",
    titleKey: "onboarding.flashcards.step6.title",
    descriptionKey: "onboarding.flashcards.step6.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-7",
    targetId: "flashcards-box-one-count",
    titleKey: "onboarding.flashcards.step7.title",
    descriptionKey: "onboarding.flashcards.step7.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-8",
    targetId: "flashcards-bubble-anchor",
    titleKey: "onboarding.flashcards.step8.title",
    descriptionKey: "onboarding.flashcards.step8.description",
    kind: "action",
    advanceOn: "box_selected",
    expectedBox: "boxOne",
  },
  {
    id: "flashcards-step-9",
    targetId: "flashcards-card-section",
    titleKey: "onboarding.flashcards.step9.title",
    descriptionKey: "onboarding.flashcards.step9.description",
    kind: "action",
    advanceOn: "answer_submitted",
    forceCorrectOnSubmit: true,
    dismissKeyboardOnAdvance: true,
  },
  {
    id: "flashcards-step-10",
    targetId: "flashcards-bubble-anchor",
    titleKey: "onboarding.flashcards.step10.title",
    descriptionKey: "onboarding.flashcards.step10.description",
    kind: "success",
    advanceOn: "forced_correct_answer_shown",
    blockOutside: true,
    successVariant: "normal",
    autoAdvanceDelayMs: 1200,
  },
  {
    id: "flashcards-step-11",
    targetId: "flashcards-box-two",
    titleKey: "onboarding.flashcards.step11.title",
    descriptionKey: "onboarding.flashcards.step11.description",
    kind: "info",
    advanceOn: "box_promoted",
    spotlight: true,
    blockOutside: true,
    autoAdvanceDelayMs: 1400,
    showDemoBoxCounts: {
      boxTwo: 1,
    },
  },
  {
    id: "flashcards-step-12",
    targetId: "flashcards-promotion-arrow-anchor",
    titleKey: "onboarding.flashcards.step12.title",
    descriptionKey: "onboarding.flashcards.step12.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    floatingIndicator: "arrow_u_down_right",
  },
  {
    id: "flashcards-step-13",
    targetId: "flashcards-boxes-section",
    titleKey: "onboarding.flashcards.step13.title",
    descriptionKey: "onboarding.flashcards.step13.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    showDemoBoxCounts: {
      boxOne: 0,
      boxTwo: 0,
      boxFive: 1,
    },
  },
  {
    id: "flashcards-step-14",
    targetId: "flashcards-boxes-section",
    titleKey: "onboarding.flashcards.step14.title",
    descriptionKey: "onboarding.flashcards.step14.description",
    kind: "success",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
    showDemoBoxCounts: {
      boxOne: 0,
      boxTwo: 0,
      boxThree: 0,
      boxFour: 0,
      boxFive: 0,
    },
    triggerDemoConfetti: true,
  },
  {
    id: "flashcards-step-15",
    targetId: "flashcards-boxes-section",
    titleKey: "onboarding.flashcards.step15.title",
    descriptionKey: "onboarding.flashcards.step15.description",
    kind: "info",
    advanceOn: "manual",
    spotlight: true,
    blockOutside: true,
  },
  {
    id: "flashcards-step-16",
    targetId: "flashcards-bubble-anchor",
    titleKey: "onboarding.flashcards.step16.title",
    descriptionKey: "onboarding.flashcards.step16.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
  },
  {
    id: "flashcards-step-17",
    targetId: "flashcards-home-button",
    titleKey: "onboarding.flashcards.step17.title",
    descriptionKey: "onboarding.flashcards.step17.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    spotlight: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-18",
    targetId: "flashcards-course-button",
    titleKey: "onboarding.flashcards.step18.title",
    descriptionKey: "onboarding.flashcards.step18.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    spotlight: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-19",
    targetId: "flashcards-stats-button",
    titleKey: "onboarding.flashcards.step19.title",
    descriptionKey: "onboarding.flashcards.step19.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    spotlight: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-20",
    targetId: "flashcards-theme-button",
    titleKey: "onboarding.flashcards.step20.title",
    descriptionKey: "onboarding.flashcards.step20.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    spotlight: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-21",
    targetId: "flashcards-review-button",
    titleKey: "onboarding.flashcards.step21.title",
    descriptionKey: "onboarding.flashcards.step21.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    spotlight: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-22",
    targetId: "flashcards-game-button",
    titleKey: "onboarding.flashcards.step22.title",
    descriptionKey: "onboarding.flashcards.step22.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    spotlight: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-23",
    targetId: "flashcards-settings-button",
    titleKey: "onboarding.flashcards.step23.title",
    descriptionKey: "onboarding.flashcards.step23.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
    spotlight: true,
    blockSpotlight: true,
  },
  {
    id: "flashcards-step-24",
    targetId: "flashcards-bubble-anchor",
    titleKey: "onboarding.flashcards.step24.title",
    descriptionKey: "onboarding.flashcards.step24.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
  },
  {
    id: "flashcards-step-25",
    targetId: "flashcards-bubble-anchor",
    titleKey: "onboarding.flashcards.step25.title",
    descriptionKey: "onboarding.flashcards.step25.description",
    kind: "info",
    advanceOn: "manual",
    blockOutside: true,
  },
];

export const FLASHCARDS_COACHMARK_STEPS: CoachmarkFlowStep[] =
  FLASHCARDS_COACHMARK_BASE_STEPS.map((step) => ({
    ...step,
    avoidTargetIds: FLASHCARDS_ACTION_BUTTON_AVOID_TARGET_IDS,
  }));
