// Centralny katalog map obrazków używanych w pakietach oficjalnych.
// Dodawaj kolejne sekcje (np. asia, animals) zamiast tworzyć nowe pliki.

export const imageMaps = {
  europeFlags: {
    "ad.svg": require("@/assets/flags/europe/ad.svg"),
    "al.svg": require("@/assets/flags/europe/al.svg"),
    "at.svg": require("@/assets/flags/europe/at.svg"),
    "ax.svg": require("@/assets/flags/europe/ax.svg"),
    "ba.svg": require("@/assets/flags/europe/ba.svg"),
    "be.svg": require("@/assets/flags/europe/be.svg"),
    "bg.svg": require("@/assets/flags/europe/bg.svg"),
    "by.svg": require("@/assets/flags/europe/by.svg"),
    "ch.svg": require("@/assets/flags/europe/ch.svg"),
    "cy.svg": require("@/assets/flags/europe/cy.svg"),
    "cz.svg": require("@/assets/flags/europe/cz.svg"),
    "de.svg": require("@/assets/flags/europe/de.svg"),
    "dk.svg": require("@/assets/flags/europe/dk.svg"),
    "ee.svg": require("@/assets/flags/europe/ee.svg"),
    "es.svg": require("@/assets/flags/europe/es.svg"),
    "eu.svg": require("@/assets/flags/europe/eu.svg"),
    "fi.svg": require("@/assets/flags/europe/fi.svg"),
    "fo.svg": require("@/assets/flags/europe/fo.svg"),
    "fr.svg": require("@/assets/flags/europe/fr.svg"),
    "gb-eng.svg": require("@/assets/flags/europe/gb-eng.svg"),
    "gb-nir.svg": require("@/assets/flags/europe/gb-nir.svg"),
    "gb-sct.svg": require("@/assets/flags/europe/gb-sct.svg"),
    "gb.svg": require("@/assets/flags/europe/gb.svg"),
    "gb-wls.svg": require("@/assets/flags/europe/gb-wls.svg"),
    "gr.svg": require("@/assets/flags/europe/gr.svg"),
    "hr.svg": require("@/assets/flags/europe/hr.svg"),
    "hu.svg": require("@/assets/flags/europe/hu.svg"),
    "ie.svg": require("@/assets/flags/europe/ie.svg"),
    "is.svg": require("@/assets/flags/europe/is.svg"),
    "it.svg": require("@/assets/flags/europe/it.svg"),
    "li.svg": require("@/assets/flags/europe/li.svg"),
    "lt.svg": require("@/assets/flags/europe/lt.svg"),
    "lu.svg": require("@/assets/flags/europe/lu.svg"),
    "lv.svg": require("@/assets/flags/europe/lv.svg"),
    "mc.svg": require("@/assets/flags/europe/mc.svg"),
    "md.svg": require("@/assets/flags/europe/md.svg"),
    "me.svg": require("@/assets/flags/europe/me.svg"),
    "mk.svg": require("@/assets/flags/europe/mk.svg"),
    "mt.svg": require("@/assets/flags/europe/mt.svg"),
    "nl.svg": require("@/assets/flags/europe/nl.svg"),
    "no.svg": require("@/assets/flags/europe/no.svg"),
    "pl.svg": require("@/assets/flags/europe/pl.svg"),
    "pt.svg": require("@/assets/flags/europe/pt.svg"),
    "ro.svg": require("@/assets/flags/europe/ro.svg"),
    "rs.svg": require("@/assets/flags/europe/rs.svg"),
    "ru.svg": require("@/assets/flags/europe/ru.svg"),
    "se.svg": require("@/assets/flags/europe/se.svg"),
    "si.svg": require("@/assets/flags/europe/si.svg"),
    "sj.svg": require("@/assets/flags/europe/sj.svg"),
    "sk.svg": require("@/assets/flags/europe/sk.svg"),
    "sm.svg": require("@/assets/flags/europe/sm.svg"),
    "ua.svg": require("@/assets/flags/europe/ua.svg"),
    "va.svg": require("@/assets/flags/europe/va.svg"),
    "xk.svg": require("@/assets/flags/europe/xk.svg"),
  },
  // Dodaj kolejne mapy tutaj, np.
  // asiaFlags: { "jp.svg": require("@/assets/flags/asia/jp.svg"), ... }
} as const;

export type EuropeFlagKey = keyof typeof imageMaps.europeFlags;
