import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

const LEGAL_TABLET_MAX_WIDTH = 500;

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollView: {
    width: "100%",
    alignSelf: "center" as const,
  },
  scrollViewTablet: {
    maxWidth: LEGAL_TABLET_MAX_WIDTH,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 56,
    gap: 16,
  },
  heroCard: {
    backgroundColor: colors.secondBackground,
    borderRadius: 24,
    padding: 20,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#00000012",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 5 },
    elevation: 3,
    gap: 12,
  },
  heroTitle: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "900",
    color: colors.headline,
  },
  heroSubtitle: {
    fontSize: 15,
    lineHeight: 22,
    color: colors.paragraph,
  },
  heroMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: 12,
  },
  onlineButton: {
    flexShrink: 0,
  },
  onlineButtonText: {
    fontSize: 16,
    lineHeight: 18,
  },
  updatedCard: {
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    height: 50,
    justifyContent: "center",
    flex: 1,
    minWidth: 0,
  },
  updatedLabel: {
    fontSize: 11,
    color: colors.paragraph,
    opacity: 0.75,
    marginBottom: 2,
  },
  updatedValue: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.headline,
  },
  sectionCard: {
    backgroundColor: colors.secondBackground,
    borderRadius: 20,
    padding: 18,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
  },
  sectionCardEmphasis: {
    borderColor: colors.my_yellow,
    shadowColor: "#00000010",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  sectionTitle: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: "900",
    color: colors.headline,
  },
  sectionBody: {
    fontSize: 14,
    lineHeight: 21,
    color: colors.paragraph,
  },
  bulletList: {
    gap: 10,
  },
  bulletRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
  },
  bulletDot: {
    width: 8,
    height: 8,
    borderRadius: 999,
    marginTop: 7,
    backgroundColor: colors.my_green,
  },
  bulletText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 21,
    color: colors.paragraph,
  },
  inlineNote: {
    borderRadius: 14,
    padding: 14,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 6,
  },
  inlineNoteLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: colors.headline,
    letterSpacing: 0.3,
  },
  emailChip: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
  },
  emailChipText: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.headline,
  },
}));
