import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const usePeekStyles = createThemeStylesHook((colors) => ({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  dialog: {
    width: "100%",
    maxWidth: 420,
    borderRadius: 24,
    backgroundColor: colors.secondBackground,
    padding: 0,
    shadowColor: colors.darkbg,
    shadowOpacity: 0.24,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 18 },
    elevation: 16,
    gap: 10,
    overflow: "hidden",
  },
  backgroundImage: {
    position: "absolute",
    right: -260,
    bottom: -260,
    width: 640,
    height: 640,
    opacity: 0.08,
    zIndex: -1,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  sectionHeader: {
    paddingHorizontal: 28,
    paddingTop: 16,
    paddingBottom: 12,
    gap: 10,
  },
  sectionBody: {
    width: "100%",
    paddingHorizontal: 12,
    paddingTop: 10,
    paddingBottom: 16,
    flexGrow: 1,
  },
  headerContent: {
    flex: 1,
    paddingRight: 12,
  },
  title: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.headline,
    letterSpacing: 0.1,
  },
  subtitle: {
    marginTop: 2,
    color: colors.paragraph,
    fontSize: 13,
    opacity: 0.8,
    lineHeight: 18,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.my_red,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  closeIcon: {
    color: colors.lightbg,
  },
  metaBar: {
    marginTop: -2,
    alignSelf: "stretch",
    paddingHorizontal: 24,
    paddingVertical: 10,

    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
  },
  metaText: {
    color: colors.paragraph,
    fontSize: 12,
    flex: 1,
  },
  metaStrong: {
    color: colors.headline,
    fontWeight: "700",
  },
  metaPill: {
    paddingVertical: 4,
    paddingHorizontal: 10,
    borderRadius: 999,
    backgroundColor: colors.border,
  },
  metaPillText: {
    fontSize: 12,
    color: colors.headline,
    fontWeight: "600",
  },
  cardsList: {
    width: "100%",
  },
  cardsListContent: {
    paddingHorizontal: 8,
    paddingVertical: 10,
    paddingBottom: 100,
    gap: 12,
  },
  cardsListFooter: {
    height: 24,
  },
  cardWrapper: {
    position: "relative",
    borderRadius: 18,
    backgroundColor: colors.secondBackground,
    padding: 12,
    overflow: "hidden",
    shadowColor: colors.darkbg,
    shadowOpacity: 0.12,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
    borderWidth: 4,
    borderColor: colors.border,
  },
  cardContent: {
    flexDirection: "row",
    gap: 10,
  },
  cardContentSimple: {
    flexDirection: "column",
    gap: 6,
  },
  cardContentBoxZero: {
    gap: 10,
  },
  cardSide: {
    width: 64,
    alignItems: "flex-start",
    justifyContent: "space-between",
    // paddingVertical: 2,
    // backgroundColor: colors.my_red,

    // gap: 6,
  },
  cardSideLabel: {
    fontSize: 14,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.paragraph,
    opacity: 0.7,
    fontWeight: "700",
    paddingTop: 3,
  },
  cardSideIndex: {
    fontSize: 13,
    fontWeight: "700",
    color: colors.headline,
  },
  cardMain: {
    // backgroundColor: colors.my_red,
    flex: 1,
    gap: 6,
  },
  cardLine: {
    flexDirection: "row",
    // alignItems: "baseline",
    gap: 6,
    height: 24,
    display: "flex",
    alignItems: "center",
    // backgroundColor: colors.my_yellow,
  },
  cardSimpleIndex: {
    fontSize: 12,
    letterSpacing: 1,
    textTransform: "uppercase",
    color: colors.paragraph,
    opacity: 0.85,
    fontWeight: "700",
  },
  cardTag: {
    fontSize: 14,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: colors.paragraph,
    opacity: 0.7,
    fontWeight: "700",
  },
  rewers: {
    // color: colors.my_green,
  },
  cardPrimary: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.headline,
  },
  cardSecondary: {
    fontSize: 15,
    fontWeight: "600",
    color: colors.paragraph,
  },
  cardAlternatives: {
    fontSize: 13,
    color: colors.paragraph,
    lineHeight: 18,
  },
  cardAlternativesLabel: {
    fontWeight: "700",
    color: colors.headline,
  },
  emptyState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 40,
    paddingHorizontal: 28,
  },
  emptyIconWrapper: {
    marginBottom: 16,
    padding: 16,
    borderRadius: 24,
    backgroundColor: colors.background,
  },
  emptyIcon: {
    color: colors.paragraph,
    opacity: 0.5,
  },
  emptyTitle: {
    color: colors.headline,
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 8,
    textAlign: "center",
  },
  emptyDescription: {
    color: colors.paragraph,
    fontSize: 15,
    opacity: 0.8,
    textAlign: "center",
    maxWidth: 260,
    lineHeight: 22,
  },
}));
