import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

const SUPPORT_TABLET_MAX_WIDTH = 500;

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollView: {
    width: "100%",
    alignSelf: "center" as const,
  },
  scrollViewTablet: {
    maxWidth: SUPPORT_TABLET_MAX_WIDTH,
  },
  content: {
    paddingHorizontal: 16,
    paddingTop: 20,
    paddingBottom: 56,
  },
  section: {
    backgroundColor: colors.secondBackground,
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    shadowColor: "#00000011",
    shadowOpacity: 0.08,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  header: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.paragraph,
    marginBottom: 8,
  },
  subtitle: {
    fontSize: 14,
    color: colors.paragraph,
    opacity: 0.9,
    marginBottom: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    columnGap: 12,
  },
  buttonWrapper: {
    flexDirection: "row",
    justifyContent: "flex-end",
    columnGap: 12,
    marginTop: 8,
  },
  legalButtonText: {
    lineHeight: 18,
  },
  status: {
    marginTop: 10,
    fontSize: 13,
    color: colors.paragraph,
    opacity: 0.85,
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    marginTop: 2,
  },
  checkboxBox: {
    width: 22,
    height: 22,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 1,
  },
  checkboxBoxActive: {
    borderColor: colors.my_green,
  },
  checkboxDot: {
    width: 12,
    height: 12,
    borderRadius: 4,
    backgroundColor: colors.my_green,
  },
  checkboxTextGroup: {
    flex: 1,
  },
  checkboxTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.headline,
  },
  checkboxSubtitle: {
    marginTop: 3,
    fontSize: 12,
    lineHeight: 16,
    color: colors.paragraph,
    opacity: 0.78,
  },

  // Panel (diagnostics)
  panel: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    borderRadius: 22,
    marginBottom: 16,
    shadowColor: "#00000011",
    shadowOpacity: 0.12,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
    overflow: "hidden",
  },
  panelHeader: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 6,
    gap: 6,
    backgroundColor: colors.secondBackground,
  },
  panelTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.headline,
  },
  panelSubtitle: {
    fontSize: 13,
    color: colors.paragraph,
    opacity: 0.75,
    marginTop: 2,
  },
  panelBody: {
    paddingHorizontal: 16,
    paddingBottom: 16,
    paddingTop: 6,
    gap: 12,
  },
  chipBox: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  chipCheck: {
    width: 10,
    height: 10,
    borderRadius: 3,
    backgroundColor: colors.my_green,
  },
  chipText: {
    fontSize: 16,
    color: colors.headline,
    letterSpacing: 0.1,
  },
  staticList: {
    gap: 10,
  },
  staticRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  staticContent: {
    flex: 1,
  },
  staticValue: {
    marginTop: 4,
    fontSize: 13,
    color: colors.paragraph,
    opacity: 0.85,
  },
}));
