import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    position: "relative",
  },
  scrollArea: {
    flex: 1,
    alignSelf: "stretch",
  },
  scrollContent: {
    paddingBottom: 120,
    alignItems: "center",
  },
  minicontainer: {
    width: "75%",
  },
  title: {
    fontSize: 25,
    fontWeight: 900,
    color: colors.headline,
    marginTop: 20,
    marginBottom: 16,
  },
  viewModeTabsSection: {
    width: "100%",
    marginBottom: 16,
  },
  viewModeTabsAnchor: {
    width: "100%",
    alignSelf: "stretch",
  },
  viewModeTabs: {
    width: "100%",
  },
  emptyStateText: {
    marginTop: 8,
    marginBottom: 8,
    color: colors.paragraph,
    fontSize: 14,
    fontWeight: 700,
    textAlign: "center",
  },
  accordionList: {
    width: "100%",
    flexDirection: "column",
    gap: 10,
  },
  accordionItem: {
    borderStyle: "dashed",
    borderRadius: 15,
    borderWidth: 4,
    borderColor: colors.border,
    backgroundColor: colors.background,
    overflow: "hidden",
  },
  accordionHeader: {
    minHeight: 92,
    paddingHorizontal: "7%",
    paddingVertical: 12,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  accordionHeaderPressed: {
    opacity: 0.88,
  },
  headerLeft: {
    flex: 1,
    minWidth: 0,
    flexDirection: "row",
    alignItems: "center",
    marginRight: 12,
  },
  headerIconBox: {
    width: 44,
    alignItems: "center",
    justifyContent: "center",
  },
  headerIconFa: {
    color: colors.headline,
  },
  headerFlagRow: {
    flexDirection: "row",
    alignItems: "center",
  },
  headerIconCode: {
    color: colors.headline,
    fontSize: 12,
    fontWeight: 800,
    marginRight: 4,
  },
  headerIconSeparator: {
    color: colors.headline,
    fontSize: 12,
    fontWeight: 700,
    marginRight: 4,
  },
  headerIconFlag: {
    width: 22,
    height: 14,
    borderRadius: 3,
  },
  headerTextWrap: {
    flex: 1,
    minWidth: 0,
    marginLeft: 10,
  },
  headerTitle: {
    color: colors.headline,
    fontSize: 25,
    fontWeight: 900,
  },
  headerSubtitle: {
    color: colors.paragraph,
    fontSize: 12,
    fontWeight: 900,
    marginTop: 2,
  },
  headerRight: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  countPillText: {
    color: colors.headline,
    fontSize: 20,
    fontWeight: 800,
    minWidth:12,
    textAlign: "center",
  },
  chevronBox: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: "center",
    justifyContent: "center",
  },
  chevronIcon: {
    color: colors.headline,
  },
  accordionBody: {
    position: "relative",
    paddingHorizontal: 8,
    paddingTop: 8,
    paddingBottom: 4,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  accordionBodySideMaskLeft: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 6,
    backgroundColor: colors.background,
  },
  accordionBodySideMaskRight: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    width: 6,
    backgroundColor: colors.background,
  },
  accordionSectionTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: colors.headline,
    marginBottom: 10,
  },
  accordionCardsList: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
    marginBottom: 10,
  },
  subTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: colors.headline,
    marginTop: 16,
    marginBottom: 12,
  },
  groupSection: {
    width: "100%",
  },
  cardsList: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  groupHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    marginBottom: 12,
  },
  groupHeaderLine: {
    flex: 1,
    borderBottomWidth: 4,
    borderStyle: "dashed",
    borderColor: colors.border,
    marginRight: 12,
  },
  groupHeaderBadge: {
    flexDirection: "row",
    alignItems: "center",
  },
  groupHeaderLanguage: {
    flexDirection: "row",
    alignItems: "center",
  },
  groupHeaderCode: {
    fontSize: 20,
    fontWeight: 800,
    color: colors.headline,
    marginRight: 6,
  },
  groupHeaderSeparator: {
    marginHorizontal: 8,
    fontSize: 20,
    fontWeight: 800,
    color: colors.headline,
  },
  groupHeaderFlag: {
    width: 99 / 3,
    height: 66 / 3,
    borderRadius: 5,
  },
  sectionSeparator: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    marginBottom: 12,
  },
  sectionSeparatorLine: {
    flex: 1,
    borderBottomWidth: 4,
    borderStyle: "dashed",
    borderColor: colors.border,
    marginRight: 12,
  },
  sectionSeparatorBadge: {
    flexDirection: "row",
    alignItems: "center",
  },
  sectionSeparatorText: {
    fontSize: 22,
    fontWeight: 800,
    color: colors.headline,
  },
  courseCard: {
    width: "100%",
    height: 92,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.secondBackground,
    borderRadius: 15,
    paddingLeft: "7%",
    paddingRight: "7%",
    position: "relative",
    marginBottom: 12,
  },
  courseCardText: {
    flex: 1,
    fontSize: 22,
    fontWeight: 800,
    textAlign: "center",
    color: colors.headline,
    marginLeft: 8,
  },
  courseCardInfo: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
    alignItems: "flex-start",
  },
  courseCardTitleContainer: {
    width: "100%",
    overflow: "hidden",
    alignItems: "flex-start",
  },
  customCardTitle: {
    fontSize: 25,
    fontWeight: 900,
    color: colors.headline,
    textAlign: "left",
  },
  customCardMeta: {
    fontSize: 12,
    fontWeight: 900,
    color: colors.headline,
    textAlign: "left",
  },
  courseCardBadge: {
    position: "absolute",
    top: -21,
    right: "-2%",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  courseCardBadgeFlag: {
    width: 99 / 2.5,
    height: 66 / 2.5,
    borderRadius: 5,
  },
  courseCardBadgeText: {
    marginLeft: 6,
    fontSize: 20,
    fontWeight: 800,
    color: colors.headline,
  },
  flag: {
    width: 99 / 1.1,
    height: 66 / 1.1,
  },
  pinButton: {
    padding: 4,
    marginLeft: 8,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  pinCheckbox: {
    width: 32,
    height: 32,
    borderWidth: 2,
    borderRadius: 8,
    borderColor: colors.border,
    backgroundColor: colors.background,
    justifyContent: "center",
    alignItems: "center",
  },
  pinCheckboxActive: {
    borderColor: colors.my_green,
  },
  officialIconWrapper: {
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  officialFlagBadge: {
    position: "absolute",
    bottom: -3,
    right: -3,
    width: 99 / 3,
    height: 66 / 3,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  buttonscontainer: {
    width: "100%",
    paddingBottom: 24,
    backgroundColor: colors.background,
    alignItems: "center",
  },
  buttonsRow: {
    borderColor: colors.border,
    borderTopWidth: 3,
    paddingTop: 15,
    width: "75%",
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  footerNote: {
    marginTop: 16,
    fontSize: 12,
    color: colors.paragraph,
    fontStyle: "italic",
  },
  introOverlay: {
    position: "absolute",
    bottom: "30%",
    left: 0,
    right: 0,
    zIndex: 40,
    elevation: 8,
    paddingHorizontal: 4,
    paddingTop: 8,
  },
}));
