import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    position: "relative",
  },
  scrollArea: {
    flex: 1,
    alignSelf: "stretch",
  },
  scrollContent: {
    paddingBottom: 120,
    alignItems: "center",
  },
  minicontainer: {
    width: "75%",
  },
  title: {
    fontSize: 25,
    fontWeight: 900,
    color: colors.headline,
    marginTop: 20,
    marginBottom: 20,
  },
  subTitle: {
    fontSize: 18,
    fontWeight: 700,
    color: colors.headline,
    marginTop: 16,
    marginBottom: 12,
  },
  groupSection: {
    width: "100%",
  },
  cardsList: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  groupHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
    marginBottom: 12,
  },
  groupHeaderLine: {
    flex: 1,
    borderBottomWidth: 4,
    borderStyle: "dashed",
    borderColor: colors.border,
    marginRight: 12,
  },
  groupHeaderBadge: {
    flexDirection: "row",
    alignItems: "center",
  },
  groupHeaderLanguage: {
    flexDirection: "row",
    alignItems: "center",
  },
  groupHeaderCode: {
    fontSize: 20,
    fontWeight: 800,
    color: colors.headline,
    marginRight: 6,
  },
  groupHeaderSeparator: {
    marginHorizontal: 8,
    fontSize: 20,
    fontWeight: 800,
    color: colors.headline,
  },
  groupHeaderFlag: {
    width: 99 / 3,
    height: 66 / 3,
    borderRadius: 5,
  },
  courseCard: {
    width: "100%",
    height: 92,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.secondBackground,
    borderRadius: 15,
    paddingLeft: "7%",
    paddingRight: "7%",
    position: "relative",
    marginBottom: 12,
  },
  courseCardText: {
    flex: 1,
    fontSize: 22,
    fontWeight: 800,
    textAlign: "center",
    color: colors.headline,
    marginLeft: 8,
  },
  courseCardInfo: {
    flex: 1,
    marginLeft: 12,
    minWidth: 0,
    alignItems: "flex-start",
  },
  courseCardTitleContainer: {
    width: "100%",
    overflow: "hidden",
    alignItems: "flex-start",
  },
  customCardTitle: {
    fontSize: 25,
    fontWeight: 900,
    color: colors.headline,
    textAlign: "left",
  },
  customCardMeta: {
    fontSize: 12,
    fontWeight: 900,
    color: colors.headline,
    textAlign: "left",
  },
  courseCardBadge: {
    position: "absolute",
    top: -21,
    right: "-2%",
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  courseCardBadgeFlag: {
    width: 99 / 2.5,
    height: 66 / 2.5,
    borderRadius: 5,
  },
  courseCardBadgeText: {
    marginLeft: 6,
    fontSize: 20,
    fontWeight: 800,
    color: colors.headline,
  },
  flag: {
    width: 99 / 1.1,
    height: 66 / 1.1,
  },
  pinButton: {
    padding: 4,
    marginLeft: 8,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  pinCheckbox: {
    width: 32,
    height: 32,
    borderWidth: 2,
    borderRadius: 8,
    borderColor: colors.border,
    backgroundColor: colors.background,
    justifyContent: "center",
    alignItems: "center",
  },
  pinCheckboxActive: {
    borderColor: colors.my_green,
  },
  officialIconWrapper: {
    width: 64,
    height: 64,
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
  },
  officialFlagBadge: {
    position: "absolute",
    bottom: -3,
    right: -3,
    width: 99 / 3,
    height: 66 / 3,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  buttonscontainer: {
    width: "100%",
    paddingBottom: 24,
    backgroundColor: colors.background,
    alignItems: "center",
  },
  buttonsRow: {
    borderColor: colors.border,
    borderTopWidth: 3,
    paddingTop: 15,
    width: "75%",
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
  },
  nextButton: {
    width: 90,
    height: 50,
    borderRadius: 12,
    backgroundColor: colors.my_green,
    alignItems: "center",
    justifyContent: "center",
  },
  nextButtonDisabled: {
    backgroundColor: colors.border,
  },
  nextButtonLabel: {
    fontSize: 16,
    fontWeight: "900",
    textTransform: "uppercase",
    color: colors.headline,
  },
  nextButtonLabelDisabled: {
    color: colors.paragraph,
    opacity: 0.6,
  },
  footerNote: {
    marginTop: 16,
    fontSize: 12,
    color: colors.paragraph,
    fontStyle: "italic",
  },
  introOverlay: {
    position: "absolute",
    bottom: "30%",
    left: 0,
    right: 0,
    zIndex: 40,
    elevation: 8,
    paddingHorizontal: 4,
    paddingTop: 8,
  },
}));
