import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useWikiPeekStyles = createThemeStylesHook((colors) => ({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.45)",
    alignItems: "center",
    justifyContent: "center",
    padding: 16,
  },
  dialog: {
    width: "100%",
    maxWidth: 420,
    borderRadius: 24,
    backgroundColor: colors.secondBackground,
    padding: 0,
    shadowColor: colors.darkbg,
    shadowOpacity: 0.24,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 18 },
    elevation: 16,
    overflow: "hidden",
  },
  sectionHeader: {
    paddingHorizontal: 28,
    paddingTop: 16,
    paddingBottom: 12,
    gap: 10,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
  },
  headerContent: {
    flex: 1,
    paddingRight: 12,
  },
  title: {
    fontSize: 18,
    fontWeight: "700",
    color: colors.headline,
    letterSpacing: 0.1,
  },
  subtitle: {
    marginTop: 2,
    color: colors.paragraph,
    fontSize: 13,
    opacity: 0.8,
    lineHeight: 18,
  },
  closeButton: {
    width: 32,
    height: 32,
    borderRadius: 4,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.my_red,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  closeIcon: {
    color: colors.lightbg,
  },
  metaBar: {
    alignSelf: "stretch",
    paddingHorizontal: 24,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    minHeight: 40,
  },
  body: {
    paddingHorizontal: 16,
    paddingVertical: 18,
    minHeight: 200,
    backgroundColor: colors.secondBackground,
    gap: 16,
    paddingBottom: 20,
    alignItems: "flex-start",
    width: "100%",
    flex: 1,
    justifyContent: "space-between",
  },
  contentScroll: {
    alignSelf: "stretch",
    flex: 1,
  },
  contentScrollContent: {
    paddingBottom: 8,
    flexGrow: 1,
  },
  footer: {
    width: "100%",
    alignItems: "flex-end",
    paddingTop: 12,
  },
}));
