import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";
import { StyleSheet } from "react-native";
const LOGO_ASPECT_RATIO = 523 / 555;
export const useStyles = createThemeStylesHook((colors) => ({
  layout: {
    flex: 1,
    backgroundColor: colors.background,
  },
  topBarContainer: {
    backgroundColor: colors.secondBackground,
    paddingHorizontal: 14,
    paddingBottom: 0,
    overflow: "visible",
    zIndex: 10,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    height: 50,
    position: "relative",
    overflow: "visible",
  },
  leftGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  rightGroup: {
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    flex: 1,
    flexShrink: 0,
    marginLeft: 8,
  },
  content: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentInner: {
    flex: 1,
  },
  logo: {
    width: 60,
    aspectRatio: LOGO_ASPECT_RATIO,
  },
  logoButton: {
    paddingVertical: 0,
    paddingHorizontal: 2,
    borderRadius: 12,
    overflow: "visible",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: -10,
    zIndex: 12,
  },
  icon: {
    color: colors.headline,
  },
  iconButton: {
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRadius: 8,
    // marginRight: 6,
    overflow: "visible",
  },
  iconButtonPressed: {
    backgroundColor: colors.my_green,
  },
  bottomBarContainer: {
    backgroundColor: colors.secondBackground,
    paddingHorizontal: 16,
    paddingTop: 8,
  },
  bottomBar: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
  },
  bottomIconButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 8,
    borderRadius: 12,
    marginHorizontal: 4,
  },
  bottomCenterButton: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 10,
    borderRadius: 16,
    marginHorizontal: 12,
  },
  bottomIconButtonPressed: {
    backgroundColor: colors.my_green,
  },
  bottomCoachmarkOverlay: {
    ...StyleSheet.absoluteFillObject,
  },
  bottomCoachmarkTarget: {
    flex: 1,
  },
  reviewIconWrapper: {
    position: "relative",
    alignItems: "center",
    justifyContent: "center",
  },
  reviewBadge: {
    position: "absolute",
    top: 10,
    right: -10,
    minWidth: 20,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 999,
    alignItems: "center",
    justifyContent: "center",
  },
  reviewBadgeText: {
    fontWeight: "700",
    fontSize: 12,
  },
  courseButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  courseFlag: {
    width: 99 / 2.7,
    height: 66 / 2.7,
    borderRadius: 4,
  },
  customCourseIconWrapper: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    width: 32,
    height: 32,
  },
  customCourseFlag: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 99 / 5.5,
    height: 66 / 5.5,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  counterText: {
    color: colors.headline,
    fontWeight: "700",
    fontSize: 16,
    textAlign: "right",
  },
  counterButton: {
    minWidth: 90,
    minHeight: 36,
    borderRadius: 12,
    paddingHorizontal: 8,
    justifyContent: "center",
    alignItems: "flex-end",
    position: "relative",
    overflow: "visible",
  },
  counterGlow: {
    ...StyleSheet.absoluteFillObject,
    borderRadius: 12,
  },
  counterContentWrap: {
    minWidth: 72,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  counterAnimatedSlot: {
    minHeight: 22,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  counterAnimatedInner: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 6,
  },
  counterNumberWrap: {
    minWidth: 38,
    alignItems: "flex-end",
  },
  counterValueText: {
    color: colors.headline,
    fontWeight: "700",
    fontSize: 16,
    textAlign: "right",
  },
  counterIconWrap: {
    width: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  counterBurstViewport: {
    position: "absolute",
    top: 36,
    left: 0,
    right: 0,
    height: 44,
    overflow: "hidden",
  },
  counterBurstLayer: {
    paddingTop: 14,
    alignItems: "center",
    paddingRight: 0,
    paddingLeft: 30,
    gap: 6,
    overflow: "visible",
  },
  counterBurstPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: colors.secondBackground,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: "#000",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 2,
  },
  counterBurstText: {
    color: colors.headline,
    fontWeight: "700",
    fontSize: 12,
  },
  counterSparkleLayer: {
    position: "absolute",
    top: 34,
    right: 12,
    width: 54,
    height: 28,
    overflow: "visible",
  },
  counterSparkleDot: {
    position: "absolute",
    width: 6,
    height: 6,
    borderRadius: 999,
  },
  courseName: {
    marginLeft: 8,
    flexShrink: 1,
    maxWidth: 150,
    overflow: "hidden",
    // backgroundColor: colors.my_red,
  },
  courseNameText: {
    color: colors.headline,
    fontWeight: "600",
    fontSize: 16,
  },
  courseLevel: {
    marginLeft: 8,
    color: colors.headline,
    fontWeight: "600",
    fontSize: 16,
  },
  right: {
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "red",
    margin: 0,
    padding: 0,
  },
}));
