import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";
const LOGO_ASPECT_RATIO = 523 / 555;
export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flexDirection: "row",
    height: 55,
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: colors.secondBackground,
    paddingHorizontal: 14,
    overflow: "visible",
  },
  leftGroup: {
    // flex: 1,
    flexDirection: "row",
    alignItems: "center",
    // backgroundColor: "red",
    width: "25%",
  },
  centerGroup: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 8,
    // backgroundColor: "blue",
    width: "50%",
    overflow: "visible",
    position: "relative",
  },
  rightGroup: {
    // flex: 1,
    flexDirection: "row",
    justifyContent: "flex-end",
    alignItems: "center",
    display: "flex",
    // backgroundColor: "red",
    margin: 0,
    padding: 0,
    width: "25%",
  },
  logo: {
    width: 60,
    aspectRatio: LOGO_ASPECT_RATIO,
  },
  logoButton: {
    paddingVertical: 0,
    paddingHorizontal: 8,
    borderRadius: 12,
    marginHorizontal: 8,
    overflow: "visible",
    alignItems: "center",
    justifyContent: "center",
  },
  logoWrapper: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 3,
  },
  icon: {
    color: colors.headline,
  },
  iconButton: {
    paddingVertical: 4,
    paddingHorizontal: 6,
    borderRadius: 8,
    // marginRight: 6,
  },
  iconButtonPressed: {
    backgroundColor: colors.my_green,
  },
  profileButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 4,
    paddingHorizontal: 6,
  },
  profileFlag: {
    width: 99 / 2.7,
    height: 66 / 2.7,
    borderRadius: 4,
  },
  customProfileIconWrapper: {
    alignItems: "center",
    justifyContent: "center",
  },
  centerIcon: {
    width: 34,
    height: 34,
  },
  counterText: {
    marginLeft: 8,
    color: colors.headline,
    fontWeight: "700",
    fontSize: 16,
    textAlign: "right",
  },
  profileName: {
    marginLeft: 8,
    color: colors.headline,
    fontWeight: "600",
    fontSize: 16,
    flexShrink: 1,
  },
  right: {
    display: "flex",
    flexDirection: "row",
    // backgroundColor: "red",
    margin: 0,
    padding: 0,
  },
}));
