import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  tabBar: {
    flexDirection: "row",
    width: "100%",
    backgroundColor: colors.secondBackground,
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  tabButton: {
    flex: 1,
    borderRadius: 8,
    paddingVertical: 10,
    alignItems: "center",
  },
  tabButtonActive: {
    backgroundColor: colors.my_green,
  },
  tabLabel: {
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    color: colors.paragraph,
  },
  tabLabelActive: {
    color: colors.background,
  },
  content: {
    flex: 1,
    width: "100%",
  },
  scrollContent: {
    paddingBottom: 32,
  },
  sectionCard: {
    backgroundColor: colors.secondBackground,
    borderRadius: 16,
    paddingHorizontal: 16,
    paddingVertical: 18,
    marginBottom: 16,
    shadowColor: "#00000011",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
    position: "relative",
  },
  sectionHeader: {
    fontSize: 18,
    fontWeight: "800",
    color: colors.paragraph,
    marginBottom: 12,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  rowTextWrapper: {
    flex: 1,
    paddingRight: 12,
  },
  rowTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.paragraph,
  },
  rowSubtitle: {
    fontSize: 13,
    color: colors.paragraph,
    opacity: 0.75,
    marginTop: 4,
  },
  switch: {
    transform: [{ scaleX: 1.12 }, { scaleY: 1.12 }],
  },
  layoutOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  layoutOption: {
    flex: 1,
    borderRadius: 12,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: "transparent",
    backgroundColor: colors.background,
    marginHorizontal: 4,
  },
  layoutOptionActive: {
    borderColor: colors.my_green,
  },
  layoutImage: {
    width: "100%",
    aspectRatio: 1,
  },
  layoutLabel: {
    textAlign: "center",
    paddingVertical: 8,
    fontSize: 14,
    fontWeight: "600",
    color: colors.paragraph,
  },
  memoryOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  memoryOption: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: "center",
    marginHorizontal: 4,
  },
  memoryOptionActive: {
    borderColor: colors.my_green,
  },
  memoryOptionLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.paragraph,
  },
  memoryOptionLabelActive: {
    color: colors.my_green,
  },
  memoryOptionMeta: {
    fontSize: 12,
    marginTop: 4,
    color: colors.paragraph,
    opacity: 0.75,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 80,
    textAlign: "center",
    color: colors.paragraph,
  },
  buttonsContainer: {
    marginTop: 16,
    alignItems: "center",
  },
  infoText: {
    marginTop: 10,
    fontSize: 13,
    color: colors.paragraph,
    opacity: 0.75,
    textAlign: "center",
  },
  keyboardSection: {
    marginBottom: 24,
  },
  keyboardInput: {
    width: "100%",
    marginTop: 12,
    textAlign: "left",
    fontSize: 18,
    fontWeight: "600",
  },
  keyboardActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: 12,
  },
  keyboardButtonWrapper: {
    marginRight: 12,
    marginTop: 8,
  },
  messagePreview: {
    marginTop: 8,
    marginBottom: 14,
    position: "relative",
  },
  messagePreviewFloating: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    marginTop: 0,
    marginBottom: 0,
    zIndex: 40,
    elevation: 8,
  },
}));
