import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  contentWrapper: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 32,
  },
  tabBar: {
    flexDirection: "row",
    width: "100%",
    backgroundColor: colors.background,
    borderTopWidth: 1,
    borderColor: colors.border,
    paddingHorizontal: 18,
    paddingTop: 8,
    paddingBottom: 14,
  },
  tabBarInner: {
    flexDirection: "row",
    width: "100%",
    backgroundColor: colors.background,
    borderRadius: 8,
    position: "relative",
    overflow: "hidden",
  },
  tabBarThumb: {
    position: "absolute",
    top: 0,
    bottom: 0,
    borderRadius: 8,
    backgroundColor: colors.secondBackground,
  },
  tabButtonInner: {
    minHeight: 44,
    width: "100%",
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
  tabButton: {
    flex: 1,
    borderRadius: 8,
    zIndex: 2,
  },
  tabButtonActive: {},
  tabLabel: {
    fontSize: 13,
    fontWeight: "700",
    textTransform: "uppercase",
    color: colors.paragraph,
  },
  tabLabelActive: {
    color: colors.background,
  },
  tabIcon: {
    color: colors.paragraph,
    textAlign: "center",
    opacity: 0.85,
    width: 22,
  },
  tabIconActive: {
    color: colors.headline,
    opacity: 1,
  },
  content: {
    flex: 1,
    width: "100%",
  },
  scrollContent: {
    paddingBottom: 28,
  },
  sectionShell: {
    backgroundColor: colors.background,
    borderRadius: 18,
    padding: 16,
    borderWidth: 1,
    borderColor: colors.border,
  },
  sectionCard: {
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: 16,
    paddingTop: 32,
    marginBottom: 18,
    borderWidth: 0,
  },
  sectionHeader: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.headline,
    marginBottom: 14,
  },
  appearanceSectionHeader: {
    fontSize: 24,
    textTransform: "uppercase",
    fontWeight: "900",
    color: colors.headline,
    textAlign: "right",
    marginBottom: 20,
  },
  appearanceGroupLabel: {
    marginTop: 2,
    marginBottom: 8,
    fontSize: 13,
    textTransform: "uppercase",
    fontWeight: "900",
    letterSpacing: 0.4,
    color: colors.paragraph,
  },
  appearanceGroupCard: {
    backgroundColor: colors.background,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 16,
    gap: 10,
  },
  learningHeroCard: {
    backgroundColor: colors.background,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 18,
    gap: 10,
  },
  settingsHeroCard: {
    backgroundColor: colors.secondBackground,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 16,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 18,
    gap: 10,
  },
  actionCardsList: {
    rowGap: 12,
  },
  actionCard: {
    backgroundColor: colors.background,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 0,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
  },
  actionCardStandalone: {
    paddingBottom: 14,
  },
  actionCardHeader: {
    gap: 4,
  },
  actionCardTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.headline,
  },
  actionCardDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.paragraph,
    opacity: 0.82,
  },
  actionCardButtonRow: {
    alignItems: "flex-end",
  },
  actionCardSections: {
    gap: 0,
  },
  actionCardSection: {
    paddingTop: 2,
    paddingBottom: 12,
    gap: 12,
  },
  appearanceChoiceCard: {
    backgroundColor: colors.background,
    borderRadius: 14,
    padding: 0,
    borderWidth: 0,
    marginBottom: 16,
    gap: 12,
  },
  appearancePlainBlock: {
    marginBottom: 16,
    gap: 10,
  },
  appearanceBlockHeader: {
    gap: 4,
  },
  appearanceBlockTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.headline,
  },
  appearanceBlockDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.paragraph,
    opacity: 0.82,
  },
  appearanceGroupRows: {
    gap: 0,
  },
  appearanceGroupRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    columnGap: 12,
    paddingVertical: 10,
  },
  appearanceRowText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  appearanceGroupDivider: {
    height: 1,
    backgroundColor: colors.border,
    opacity: 0.75,
  },
  sectionSubheader: {
    fontSize: 13,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: colors.paragraph,
    opacity: 0.82,
    marginBottom: 10,
  },
  settingsList: {
    rowGap: 10,
  },
  settingItemCard: {
    backgroundColor: colors.background,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    padding: 12,
    gap: 10,
  },
  settingItemCardActive: {
    borderColor: colors.my_green,
    backgroundColor: `${colors.my_green}12`,
  },
  settingItemCardCompact: {
    gap: 8,
  },
  settingItemInline: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    columnGap: 12,
  },
  settingHeaderBlock: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  settingTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.headline,
  },
  settingDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.paragraph,
  },
  settingMeta: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.paragraph,
    opacity: 0.82,
  },
  settingStatus: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.headline,
    opacity: 0.88,
  },
  settingControlInline: {
    minHeight: 40,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
  },
  settingsGroup: {
    rowGap: 10,
  },
  settingsGroupTitle: {
    fontSize: 13,
    fontWeight: "900",
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: colors.paragraph,
    opacity: 0.8,
    marginBottom: 2,
    paddingHorizontal: 2,
  },
  settingsDivider: {
    height: 1,
    backgroundColor: colors.border,
    opacity: 0.8,
    marginVertical: 14,
    marginHorizontal: 2,
  },
  statusCard: {
    backgroundColor: colors.background,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 2,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statusTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    columnGap: 8,
    marginBottom: 6,
  },
  statusTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: colors.headline,
  },
  statusTitleIcon: {
    color: colors.headline,
    opacity: 0.9,
  },
  row: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 6,
  },
  rowTextWrapper: {
    flex: 1,
    paddingRight: 12,
  },
  rowTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: colors.headline,
  },
  rowSubtitle: {
    fontSize: 14,
    color: colors.paragraph,
    opacity: 0.82,
    marginTop: 4,
    lineHeight: 20,
  },
  appearanceRowTitle: {
    fontSize: 16,
    fontWeight: "800",
    color: colors.headline,
  },
  appearanceRowSubtitle: {
    fontSize: 14,
    color: colors.paragraph,
    opacity: 0.82,
    marginTop: 4,
    lineHeight: 20,
  },
  driveButtonText: {
    fontSize: 15,
    fontWeight: "900",
    textTransform: "uppercase",
    textAlign: "center",
  },
  snapshotList: {
    rowGap: 10,
    marginTop: 6,
  },
  snapshotCard: {
    backgroundColor: colors.background,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingTop: 14,
    paddingBottom: 12,
    borderWidth: 1,
    borderColor: colors.border,
  },
  snapshotMain: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    columnGap: 12,
  },
  snapshotMainCompact: {
    flexDirection: "column",
    alignItems: "stretch",
    rowGap: 12,
  },
  snapshotCardText: {
    flex: 1,
    minWidth: 0,
  },
  snapshotTopline: {
    flexDirection: "row",
    alignItems: "center",
    columnGap: 8,
    minWidth: 0,
  },
  snapshotStatusDot: {
    width: 10,
    height: 10,
    borderRadius: 999,
    flexShrink: 0,
  },
  snapshotStatusDotOk: {
    backgroundColor: colors.my_green,
  },
  snapshotStatusDotWarn: {
    backgroundColor: colors.my_yellow,
  },
  snapshotStatusDotBad: {
    backgroundColor: "#ff7f98",
  },
  snapshotTitle: {
    fontSize: 16,
    fontWeight: "900",
    color: colors.headline,
    flexShrink: 1,
  },
  snapshotSubtitle: {
    fontSize: 14,
    color: colors.paragraph,
    opacity: 0.82,
    marginTop: 4,
    lineHeight: 20,
  },
  snapshotWarning: {
    fontSize: 13,
    color: colors.my_yellow,
    marginTop: 6,
    fontWeight: "700",
  },
  snapshotButton: {
    width: 112,
    borderRadius: 14,
    height: 46,
  },
  snapshotButtonCompact: {
    width: "100%",
  },
  snapshotButtonText: {
    fontSize: 14,
    fontWeight: "900",
  },
  snapshotFooter: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-end",
    marginTop: 12,
  },
  snapshotDetailsToggle: {
    paddingVertical: 6,
  },
  snapshotDetailsToggleText: {
    fontSize: 13,
    fontWeight: "800",
    color: colors.paragraph,
    opacity: 0.7,
  },
  snapshotDetails: {
    marginTop: 12,
    padding: 12,
    borderRadius: 14,
    backgroundColor: colors.secondBackground,
    borderWidth: 1,
    borderColor: colors.border,
  },
  snapshotDetailsTitle: {
    fontSize: 11,
    fontWeight: "900",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    color: colors.paragraph,
    opacity: 0.65,
    marginBottom: 6,
  },
  snapshotDetailsText: {
    fontSize: 14,
    color: colors.paragraph,
    lineHeight: 20,
  },
  snapshotEmptyText: {
    fontSize: 14,
    color: colors.paragraph,
    opacity: 0.82,
    marginTop: 2,
    marginBottom: 2,
  },
  sliderSection: {
    paddingTop: 2,
  },
  sliderRow: {
    alignItems: "center",
    justifyContent: "space-between",
    columnGap: 8,
    flexDirection: "row",
    marginTop: 10,
  },
  slider: {
    height: 40,
    // width: "100%",
    // transform: [{ scaleY: 4 }], // spróbuj 1.3–2
  },
  sliderWrapper: {
    flex: 1,
    height: 44,
    borderRadius: 22,
    justifyContent: "center",
    overflow: "visible",
  },
  sliderTrack: {
    position: "absolute",
    left: 0,
    right: 0,
    height: 12,
    borderRadius: 10,
    marginVertical: 16,
    backgroundColor: colors.border,
  },
  sliderFill: {
    position: "absolute",
    left: 0,
    height: 12,
    borderRadius: 10,
    marginVertical: 16,
    backgroundColor: colors.my_green,
  },
  sliderThumb: {
    position: "absolute",
    top: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.background,
    borderWidth: 2,
    borderColor: colors.my_green,
    elevation: 3,
    shadowColor: "#00000033",
    shadowOpacity: 0.2,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  sliderValue: {
    width: 56,
    textAlign: "right",
    fontSize: 16,
    fontWeight: "800",
    color: colors.paragraph,
    transform: [{ translateX: -5 }],
  },
  sliderDisabled: {
    opacity: 0.35,
  },
  switch: {
    transform: [{ scaleX: 1.04 }, { scaleY: 1.04 }],
  },
  layoutOptionsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    width: "100%",
    justifyContent: "space-between",
    columnGap: 12,
    marginTop: 6,
  },
  languageSegment: {
    flexDirection: "column",
    alignItems: "stretch",
    width: "100%",
    marginTop: 2,
  },
  languageSelectTrigger: {
    minHeight: 48,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  languageSelectTriggerText: {
    fontSize: 15,
    fontWeight: "800",
    color: colors.headline,
  },
  languageSelectChevron: {
    fontSize: 20,
    fontWeight: "800",
    lineHeight: 20,
    color: colors.headline,
    opacity: 0.95,
  },
  languageModalBackdrop: {
    flex: 1,
    backgroundColor: "#00000055",
    justifyContent: "center",
    paddingHorizontal: 24,
  },
  languageModalCard: {
    borderRadius: 14,
    backgroundColor: colors.secondBackground,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: 8,
    overflow: "hidden",
  },
  languageMenuOption: {
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  languageMenuOptionActive: {
    backgroundColor: `${colors.my_green}20`,
  },
  languageMenuOptionText: {
    fontSize: 15,
    fontWeight: "700",
    color: colors.paragraph,
  },
  languageMenuOptionTextActive: {
    color: colors.my_green,
  },
  layoutOption: {
    flex: 1,
    flexBasis: 0,
    minWidth: 0,
    borderRadius: 14,
    overflow: "hidden",
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    paddingTop: 0,
    paddingBottom: 10,
    alignItems: "center",
  },
  layoutOptionActive: {
    borderColor: colors.my_green,
  },
  layoutPreviewWrapper: {
    width: "100%",
    aspectRatio: 1.2,
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
  },
  layoutPreview: {
    width: "100%",
    height: "100%",
  },
  layoutPreviewImage: {
    transform: [{ scale: 1.3 }, { translateY: 11 }],

  },
  actionPreviewImage: {
    transform: [{ scale: 2.7 }, { translateY: 11 }],
  },
  layoutLabel: {
    fontSize: 14,
    fontWeight: "800",
    color: colors.headline,
    textAlign: "center",
    borderTopWidth: 1,
    borderColor: colors.border,
    width: "100%",
    paddingTop: 10,
  },
  layoutLabelActive: {
    color: colors.headline,
  },
  actionOptionsRow: {
    flexDirection: "row",
    alignItems: "stretch",
    width: "100%",
    justifyContent: "space-between",
    columnGap: 12,
    marginTop: 6,
  },
  actionOption: {
    minWidth: 0,
  },
  memoryOptions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 12,
  },
  memoryOption: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: "center",
    marginHorizontal: 4,
  },
  memoryOptionActive: {
    borderColor: colors.my_green,
  },
  memoryOptionLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.paragraph,
  },
  memoryOptionLabelActive: {
    color: colors.my_green,
  },
  memoryOptionMeta: {
    fontSize: 12,
    marginTop: 4,
    color: colors.paragraph,
    opacity: 0.75,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    minWidth: 80,
    textAlign: "center",
    color: colors.paragraph,
  },
  buttonsContainer: {
    marginTop: 16,
    alignItems: "center",
  },
  infoText: {
    marginTop: 10,
    fontSize: 14,
    color: colors.paragraph,
    opacity: 0.82,
    textAlign: "center",
  },
  keyboardSection: {
    marginBottom: 24,
  },
  keyboardInput: {
    width: "100%",
    marginTop: 12,
    textAlign: "left",
    fontSize: 18,
    fontWeight: "600",
  },
  keyboardActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    marginTop: 12,
  },
  keyboardButtonWrapper: {
    marginRight: 12,
    marginTop: 8,
  },
  messagePreview: {
    marginTop: 8,
    marginBottom: 14,
    position: "relative",
  },
  messagePreviewFloating: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    marginTop: 0,
    marginBottom: 0,
    zIndex: 40,
    elevation: 8,
  },
}));
