import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollContent: {
    paddingHorizontal: 18,
    paddingBottom: 120,
    paddingTop: 32,
    gap: 0,
  },
  scrollContentWithManualToolbar: {
    paddingBottom: 320,
  },
  topSection: {
    gap: 12,
  },
  topSectionTitle: {
    fontSize: 24,
    fontWeight: "900" as const,
    textTransform: "uppercase" as const,
    color: colors.headline,
    textAlign: "right" as const,
    paddingRight: 10,
  },
  viewModeTabs: {
    width: "100%",
  },
  sectionCard: {
    backgroundColor: colors.background,
    borderRadius: 16,
    padding: 16,
    paddingTop: 32,
    gap: 18,
  },
  sectionHeader: {
    fontSize: 24,
    fontWeight: "900",
    textTransform: "uppercase" as const,
    color: colors.headline,
  },
  sectionDescription: {
    fontSize: 14,
    color: colors.paragraph,
  },
  sectionGroup: {
    gap: 0,
  },
  sectionLabel: {
    fontSize: 16,
    fontWeight: "900",
    textTransform: "uppercase" as const,
    color: colors.headline,
  },
  toggleRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    gap: 12,
  },
  toggleTextWrapper: {
    flex: 1,
    paddingRight: 12,
  },
  toggleTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: colors.paragraph,
  },
  toggleSubtitle: {
    fontSize: 13,
    color: colors.paragraph,
    opacity: 0.75,
    marginTop: 4,
  },
  switch: {
    transform: [{ scaleX: 1.12 }, { scaleY: 1.12 }],
  },
  settingsSectionHeader: {
    fontSize: 24,
    textTransform: "uppercase" as const,
    fontWeight: "900",
    color: colors.headline,
    textAlign: "right" as const,
    marginBottom: 20,
  },
  settingsGroupLabel: {
    marginTop: 2,
    marginBottom: 8,
    fontSize: 13,
    textTransform: "uppercase" as const,
    fontWeight: "900",
    letterSpacing: 0.4,
    color: colors.paragraph,
  },
  settingsGroupCard: {
    backgroundColor: colors.background,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: colors.border,
    marginBottom: 16,
    gap: 10,
  },
  settingsGroupRows: {
    gap: 0,
  },
  settingsGroupRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "space-between" as const,
    columnGap: 12,
    paddingVertical: 10,
  },
  settingsGroupDivider: {
    height: 1,
    backgroundColor: colors.border,
    opacity: 0.75,
  },
  settingsRowText: {
    flex: 1,
    minWidth: 0,
    paddingRight: 8,
  },
  settingsRowTitle: {
    fontSize: 16,
    fontWeight: "800" as const,
    color: colors.headline,
  },
  settingsRowDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.paragraph,
    opacity: 0.82,
    marginTop: 4,
  },
  settingsDependentRow: {
    paddingLeft: 12,
  },
  settingsDependentRowDisabled: {
    opacity: 0.58,
  },
  settingsChoiceBlock: {
    backgroundColor: colors.background,
    borderRadius: 14,
    borderColor: colors.border,
    marginBottom: 16,
    gap: 6,
  },
  settingsChoiceHeader: {
    gap: 4,
  },
  settingsChoiceTitle: {
    fontSize: 16,
    fontWeight: "800" as const,
    color: colors.headline,
  },
  settingsChoiceDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.paragraph,
    opacity: 0.82,
  },
  settingsChoiceHint: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.paragraph,
    opacity: 0.72,
  },
  settingsChoiceGrid: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 10,
  },
  settingsChoiceOption: {
    flexGrow: 1,
    flexBasis: 0,
    minWidth: "48%",
    borderRadius: 14,
    borderWidth: 2,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 4,
  },
  settingsChoiceOptionActive: {
    borderColor: colors.my_green,
  },
  settingsChoiceOptionDisabled: {
    opacity: 0.5,
  },
  settingsChoiceOptionTitle: {
    fontSize: 15,
    fontWeight: "800" as const,
    color: colors.headline,
  },
  settingsChoiceOptionDescription: {
    fontSize: 13,
    lineHeight: 18,
    color: colors.paragraph,
    opacity: 0.8,
  },
  settingsActionCard: {
    backgroundColor: colors.background,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingTop: 0,
    paddingBottom: 0,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 12,
  },
  settingsActionCardStandalone: {
    paddingBottom: 0,
  },
  settingsActionCardSections: {
    gap: 0,
  },
  settingsActionCardSection: {
    paddingTop: 14,
    paddingBottom: 14,
    gap: 12,
  },
  settingsActionCardHeader: {
    gap: 4,
  },
  settingsActionCardTitle: {
    fontSize: 16,
    fontWeight: "800" as const,
    color: colors.headline,
  },
  settingsActionCardDescription: {
    fontSize: 14,
    lineHeight: 20,
    color: colors.paragraph,
    opacity: 0.82,
  },
  settingsActionCardButtonRow: {
    alignItems: "flex-end" as const,
  },
  iconSection: {
    gap: 12,
  },
  iconSelectorWrapper: {
    gap: 12,
  },
  iconsContainer: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    width: "100%",
    justifyContent: "flex-start" as const,
  },
  iconWrapper: {
    flexBasis: "20%",
    alignItems: "center" as const,
    justifyContent: "center" as const,
    marginBottom: 6,
    padding: 8,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: "transparent",
  },
  iconWrapperSelected: {
    borderColor: colors.my_green,
  },
  colorsContainer: {
    width: "100%",
    justifyContent: "flex-start" as const,
  },
  courseColor: {
    flex: 1,
    aspectRatio: 1,
    borderRadius: 12,
  },
  courseColorSelected: {
    borderWidth: 3,
    borderColor: colors.my_green,
  },
  manualHeader: {
    gap: 0,
  },
  manualToolbarWrap: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 10,
    backgroundColor: colors.background,
    // borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  manualToolbar: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 10,
  },
  manualTypeSelector: {
    flex: 1,
  },
  manualAddButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: colors.my_yellow,
    borderWidth: 1,
    borderColor: colors.border,
  },
  manualAddIcon: {
    fontSize: 28,
    lineHeight: 28,
    fontWeight: "900" as const,
    color: colors.headline,
  },
  manualHistoryRow: {
    marginTop: 16,
    flexDirection: "row" as const,
    justifyContent: "flex-end" as const,
  },
  manualHistoryButton: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    backgroundColor: colors.secondBackground,
    borderWidth: 2,
    borderColor: colors.border,
  },
  manualHistoryButtonDisabled: {
    opacity: 0.4,
  },
  manualHistoryButtonText: {
    fontSize: 14,
    fontWeight: "700",
    color: colors.headline,
  },
  footerButtons: {
    marginTop: 24,
    flexDirection: "row" as const,
    justifyContent: "flex-end" as const,
    gap: 12,
  },
  footerBar: {
    paddingHorizontal: 24,
    paddingBottom: 24,
    paddingTop: 16,
    borderTopWidth: 2,
    borderTopColor: colors.border,
    backgroundColor: colors.background,
    alignItems: "flex-end" as const,
  },
  footerButtonsRow: {
    borderColor: colors.border,
    borderTopWidth: 3,
    paddingTop: 15,
    width: "75%",
    flexDirection: "row" as const,
    justifyContent: "flex-end" as const,
    gap: 10,
  },
  buttonscontainer: {
    width: "100%",
    paddingBottom: 24,
    backgroundColor: colors.background,
    alignItems: "center",
  },
  buttonsRow: {
    borderColor: colors.border,
    borderTopWidth: 3,
    paddingTop: 15,
    width: "90%",
    flexDirection: "row",
    alignItems: "center",
    // klucz: rozciągamy środek, więc nie potrzebujemy już flex-end
    justifyContent: "flex-start",
    gap: 10,
  },
  spacer: {
    flex: 1, // zajmuje całe wolne miejsce
  },
  rightGroup: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
}));
