import { DEFAULT_FLASHCARDS_BATCH_SIZE } from "@/src/config/appConfig";
import { resolveThemeColors } from "@/src/theme/theme";
import { DEFAULT_MANUAL_REMINDER_HOUR } from "@/src/services/smartReminders";
import type {
  CourseAutoflowOverrides,
  CourseBoxZeroOverrides,
  CourseCardSizeOverrides,
  CourseExplanationOnlyOnWrongOverrides,
  CourseImageFrameOverrides,
  CourseImageSizeOverrides,
  CourseShowExplanationOverrides,
  CourseSkipCorrectionOverrides,
  CourseTrueFalseButtonsOverrides,
  CustomCourseEntrySettingsSeenMap,
  SettingsContextValue,
} from "./types";

export const DEFAULT_COURSE_BOX_ZERO_OVERRIDES: CourseBoxZeroOverrides = {
  builtin: {},
  custom: {},
};

export const DEFAULT_COURSE_AUTOFLOW_OVERRIDES: CourseAutoflowOverrides = {
  builtin: {},
  custom: {},
};

export const DEFAULT_COURSE_SHOW_EXPLANATION_OVERRIDES: CourseShowExplanationOverrides = {
  builtin: {},
  custom: {},
};

export const DEFAULT_COURSE_EXPLANATION_ONLY_ON_WRONG_OVERRIDES: CourseExplanationOnlyOnWrongOverrides = {
  builtin: {},
  custom: {},
};

export const DEFAULT_CUSTOM_COURSE_ENTRY_SETTINGS_SEEN: CustomCourseEntrySettingsSeenMap = {};

export const DEFAULT_COURSE_CARD_SIZE_OVERRIDES: CourseCardSizeOverrides = {
  builtin: {},
  custom: {},
};

export const DEFAULT_COURSE_SKIP_CORRECTION_OVERRIDES: CourseSkipCorrectionOverrides = {
  builtin: {},
  custom: {},
};

export const DEFAULT_COURSE_IMAGE_SIZE_OVERRIDES: CourseImageSizeOverrides = {
  builtin: {},
  custom: {},
};

export const DEFAULT_COURSE_IMAGE_FRAME_OVERRIDES: CourseImageFrameOverrides = {
  builtin: {},
  custom: {},
};

export const DEFAULT_COURSE_TRUE_FALSE_BUTTONS_OVERRIDES: CourseTrueFalseButtonsOverrides = {
  builtin: {},
  custom: {},
};

export const defaultValue: SettingsContextValue = {
  uiLanguage: "pl",
  nativeLanguage: "pl",
  resolvedLanguage: "pl",
  setUiLanguage: async () => {},
  setNativeLanguage: async () => {},
  theme: "light",
  colors: resolveThemeColors("light"),
  toggleTheme: async () => {},
  boxesLayout: "classic",
  setBoxesLayout: async () => {},
  actionButtonsPosition: "bottom",
  setActionButtonsPosition: async () => {},
  courses: [],
  addCourse: async () => {},
  removeCourse: async () => {},
  selectedLevel: "A1",
  setLevel: () => {},
  spellChecking: true,
  toggleSpellChecking: async () => {},
  ignoreDiacriticsInSpellcheck: false,
  toggleIgnoreDiacriticsInSpellcheck: async () => {},
  showBoxFaces: true,
  toggleShowBoxFaces: async () => {},
  boxZeroEnabled: false,
  getBuiltinCourseBoxZeroEnabled: () => false,
  setBuiltinCourseBoxZeroEnabled: async () => {},
  getCustomCourseBoxZeroEnabled: () => false,
  setCustomCourseBoxZeroEnabled: async () => {},
  autoflowEnabled: true,
  getBuiltinCourseAutoflowEnabled: () => true,
  setBuiltinCourseAutoflowEnabled: async () => {},
  getCustomCourseAutoflowEnabled: () => true,
  setCustomCourseAutoflowEnabled: async () => {},
  showExplanationEnabled: true,
  getBuiltinCourseShowExplanationEnabled: () => true,
  setBuiltinCourseShowExplanationEnabled: async () => {},
  getCustomCourseShowExplanationEnabled: () => true,
  setCustomCourseShowExplanationEnabled: async () => {},
  explanationOnlyOnWrong: false,
  getBuiltinCourseExplanationOnlyOnWrong: () => false,
  setBuiltinCourseExplanationOnlyOnWrong: async () => {},
  getCustomCourseExplanationOnlyOnWrong: () => false,
  setCustomCourseExplanationOnlyOnWrong: async () => {},
  skipCorrectionEnabled: false,
  getBuiltinCourseSkipCorrectionEnabled: () => false,
  setBuiltinCourseSkipCorrectionEnabled: async () => {},
  getCustomCourseSkipCorrectionEnabled: () => false,
  setCustomCourseSkipCorrectionEnabled: async () => {},
  trueFalseButtonsVariant: "true_false",
  getBuiltinCourseTrueFalseButtonsVariant: () => "true_false",
  setBuiltinCourseTrueFalseButtonsVariant: async () => {},
  getCustomCourseTrueFalseButtonsVariant: () => "true_false",
  setCustomCourseTrueFalseButtonsVariant: async () => {},
  resetLearningSettings: async () => {},
  resetActiveCourseReviews: async () => 0,
  resetActiveCustomCourseReviews: async () => 0,
  resetOnboardingState: async () => {},
  activeCourseIdx: null,
  setActiveCourseIdx: async () => {},
  activeCourse: null,
  activeCustomCourseId: null,
  setActiveCustomCourseId: async () => {},
  customCourseEntrySettingsSeenHydrated: false,
  hasSeenCustomCourseEntrySettings: () => false,
  markCustomCourseEntrySettingsSeen: async () => {},
  pinnedOfficialCourseIds: [],
  pinOfficialCourse: async () => {},
  unpinOfficialCourse: async () => {},
  flashcardsBatchSize: DEFAULT_FLASHCARDS_BATCH_SIZE,
  setFlashcardsBatchSize: async () => {},
  flashcardsSuggestionsEnabled: true,
  toggleFlashcardsSuggestions: async () => {},
  quotesEnabled: true,
  toggleQuotesEnabled: async () => {},
  flashcardsCardSize: "large",
  flashcardsImageSize: "dynamic",
  flashcardsImageFrameEnabled: true,
  dailyGoal: 20,
  setDailyGoal: async () => {},
  feedbackEnabled: true,
  setFeedbackEnabled: async () => {},
  toggleFeedbackEnabled: async () => {},
  feedbackVolume: 1,
  setFeedbackVolume: async () => {},
  learningRemindersEnabled: false,
  setLearningRemindersEnabled: async () => {},
  toggleLearningRemindersEnabled: async () => {},
  learningReminderAutomaticEnabled: true,
  setLearningReminderAutomaticEnabled: async () => {},
  learningReminderManualHour: DEFAULT_MANUAL_REMINDER_HOUR,
  setLearningReminderManualHour: async () => {},
  learningReminderNextAt: null,
  learningReminderProfile: "unknown",
  learningReminderPermissionState: "undetermined",
  refreshLearningReminderSchedule: async () => {},
  cancelTodayLearningReminderSchedule: async () => {},
  googleDriveConfigured: false,
  googleDriveConfigurationError: null,
  googleDriveConnected: false,
  lastSuccessfulGoogleDriveBackupAt: null,
  lastGoogleDriveBackupAttemptAt: null,
  googleDriveBackupError: null,
  googleDriveBackupSnapshots: [],
  googleDriveBackupSnapshotsLoading: false,
  googleDriveBackupSnapshotsError: null,
  googleDriveBackupInProgress: false,
  googleDriveRestoreInProgress: false,
  connectGoogleDriveBackup: async () => ({ connected: false, cancelled: true }),
  disconnectGoogleDriveBackup: async () => {},
  backupUserDataToGoogleDriveNow: async () => {},
  restoreUserDataFromGoogleDrive: async () => ({ success: false }),
  refreshGoogleDriveBackupSnapshots: async () => {},
  applyImportedAppState: async () => {},
  statsFireEffectEnabled: false,
  setStatsFireEffectEnabled: async () => {},
  toggleStatsFireEffectEnabled: async () => {},
  statsBookshelfEnabled: false,
  setStatsBookshelfEnabled: async () => {},
  toggleStatsBookshelfEnabled: async () => {},
  flashcardsCardSizeDefault: "large",
  setFlashcardsCardSizeDefault: async () => {},
  getBuiltinCourseCardSize: () => "large",
  setBuiltinCourseCardSize: async () => {},
  getCustomCourseCardSize: () => "large",
  setCustomCourseCardSize: async () => {},
  flashcardsImageSizeDefault: "dynamic",
  setFlashcardsImageSizeDefault: async () => {},
  getBuiltinCourseImageSize: () => "dynamic",
  setBuiltinCourseImageSize: async () => {},
  getCustomCourseImageSize: () => "dynamic",
  setCustomCourseImageSize: async () => {},
  flashcardsImageFrameDefaultEnabled: true,
  setFlashcardsImageFrameDefaultEnabled: async () => {},
  getBuiltinCourseImageFrameEnabled: () => true,
  setBuiltinCourseImageFrameEnabled: async () => {},
  getCustomCourseImageFrameEnabled: () => true,
  setCustomCourseImageFrameEnabled: async () => {},
  highContrastEnabled: false,
  toggleHighContrast: async () => {},
  colorBlindMode: "none",
  setColorBlindMode: async () => {},
  toggleColorBlindMode: async () => {},
  largeFontEnabled: false,
  toggleLargeFont: async () => {},
  correctionErrorMarkersEnabled: true,
  toggleCorrectionErrorMarkers: async () => {},
  fontScaleMultiplier: 1,
  memoryBoardSize: "twoByThree",
  setMemoryBoardSize: async () => {},
  accessibilityPreferences: {
    highContrastEnabled: false,
    colorBlindMode: "none",
    largeFontEnabled: false,
    correctionErrorMarkersEnabled: true,
  },
};
