import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scrollArea: {
    flex: 1,
    alignSelf: "stretch",
  },
  scrollContent: {
    paddingBottom: 32,
    alignItems: "center",
  },
  minicontainer: {
    width: "75%",
    gap: 16,
    paddingTop: 24,
  },
  title: {
    fontSize: 26,
    fontWeight: "900",
    color: colors.headline,
    textAlign: "right",
  },
  section: {
    gap: 12,
  },
  courseGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  groupContainer: {
    width: "100%",
    marginBottom: 16,
  },
  groupHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
    marginBottom: 12,
  },
  groupHeaderLine: {
    flex: 1,
    borderBottomWidth: 4,
    borderStyle: "dashed",
    borderColor: colors.border,
    marginRight: 12,
  },
  groupHeaderBadge: {
    flexDirection: "row",
    alignItems: "center",
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  groupHeaderLanguage: {
    flexDirection: "row",
    alignItems: "center",
  },
  groupHeaderCode: {
    fontSize: 20,
    fontWeight: "800",
    color: colors.headline,
    marginRight: 6,
  },
  groupHeaderSeparator: {
    marginHorizontal: 8,
    fontSize: 20,
    fontWeight: "800",
    color: colors.headline,
  },
  groupHeaderFlag: {
    width: 99 / 3,
    height: 66 / 3,
    borderRadius: 5,
  },
  sectionTitle: {
    fontSize: 25,
    fontWeight: 900,
    color: colors.headline,
  },
  miniSectionTitle: {
    fontSize: 20,
    fontWeight: 800,
    color: colors.headline,
  },
  courseCard: {
    width: 145,
    height: 145,
    display: "flex",
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: colors.secondBackground,
    borderRadius: 15,
    aspectRatio: 1,
    // padding: 16,
    marginBottom: 20,
    // paddingLeft: "10%",
    // paddingRight: "6%",
    position: "relative",
  },
  courseCardDisabled: {
    opacity: 0.8,
  },
  courseCardContent: {
    height: "100%",
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    justifyContent: "center",
  },
  courseCardTitleContainer: {
    width: "80%",
    overflow: "hidden",
    alignItems: "center",
  },
  courseCardText: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.headline,
  },
  courseCardIconFlag: {
    width: 64,
    height: 48,
    borderRadius: 8,
  },
  courseCount: {
    position: "absolute",
    bottom: 12,
    right: 12,
  },
  courseCardBadge: {
    position: "absolute",
    top: -21,
    right: 0,
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  courseCardBadgeFlag: {
    width: 99 / 2.5,
    height: 66 / 2.5,
    borderRadius: 5,
  },
  courseCardBadgeText: {
    marginLeft: 6,
    fontSize: 22,
    fontWeight: "800",
    color: colors.headline,
  },
  countBadge: {
    minWidth: 72,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.background,
  },
  countNumber: {
    fontSize: 22,
    fontWeight: "900",
    minWidth: 34,
    paddingHorizontal: 4,
    textAlign: "center",
    textAlignVertical: "center",
    // backgroundColor: colors.border,
  },
  countLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.paragraph,
  },
  flag: {
    width: 99 / 1.3,
    height: 66 / 1.3,
  },
  customList: {
    flexDirection: "column",
    gap: 12,
  },
  customCard: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderRadius: 15,
    paddingLeft: "10%",
    paddingRight: "10%",
    backgroundColor: colors.secondBackground,
    height: 92,
  },
  customCardContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    flex: 1,
  },
  customCardInfo: {
    gap: 4,
  },
  customCardTitle: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.headline,
  },
  customCardMeta: {
    fontSize: 12,
    fontWeight: "700",
    color: colors.paragraph,
  },
  emptyText: {
    color: colors.paragraph,
    fontStyle: "italic",
  },
}));
