import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  root: {
    gap: 16,
  },
  sectionLabel: {
    fontSize: 12,
    textTransform: "uppercase" as const,
    fontWeight: "900" as const,
    color: colors.paragraph,
    letterSpacing: 0.9,
  },
  sectionDescription: {
    marginTop: 4,
    fontSize: 12,
    color: colors.paragraph,
  },
  previewIcon: {
    color: colors.headline,
  },
  previewCard: {
    padding: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    gap: 14,
  },
  previewRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 12,
  },
  previewBadge: {
    width: 52,
    height: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    flexShrink: 0 as const,
    overflow: "hidden" as const,
    position: "relative" as const,
  },
  previewColorOverlay: {
    position: "absolute" as const,
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    opacity: 0.12,
  },
  previewTextWrap: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  previewTitle: {
    fontSize: 16,
    fontWeight: "900" as const,
    color: colors.headline,
  },
  previewMetaRow: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 8,
    alignItems: "center" as const,
  },
  previewHint: {
    fontSize: 12,
    color: colors.paragraph,
  },
  sectionCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    padding: 16,
    gap: 12,
  },
  sectionHeaderBlock: {
    gap: 2,
  },
  nameInput: {
    minHeight: 50,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    paddingHorizontal: 14,
    fontSize: 16,
    color: colors.headline,
    fontWeight: "700" as const,
  },
  nameInputError: {
    borderColor: colors.my_red,
  },
  nameInputWarning: {
    borderColor: colors.my_yellow,
  },
  nameFeedback: {
    marginTop: -2,
    fontSize: 13,
    fontWeight: "600" as const,
  },
  nameFeedbackError: {
    color: colors.my_red,
  },
  nameFeedbackWarning: {
    color: colors.my_yellow,
  },
  pickerRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 12,
  },
  pickerLeft: {
    flex: 1,
    minWidth: 0,
    gap: 10,
  },
  colorSwatchMini: {
    width: 12,
    height: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
  },
  pickerTitle: {
    fontSize: 14,
    fontWeight: "900" as const,
    color: colors.headline,
  },
  pickerDescription: {
    marginTop: -6,
    fontSize: 12,
    color: colors.paragraph,
  },
  changeIconButton: {
    width: 44,
    height: 44,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    shadowColor: "#000000",
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  changeIconButtonDisabled: {
    opacity: 0.45,
  },
  changeIconButtonIcon: {
    color: colors.headline,
  },
  changeButtonPressed: {
    opacity: 0.85,
  },
  chipRow: {
    flexDirection: "row" as const,
    gap: 8,
    flexWrap: "wrap" as const,
  },
  chip: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
    maxWidth: "100%",
  },
  chipStrong: {
    fontSize: 12,
    fontWeight: "900" as const,
    color: colors.headline,
  },
  chipMono: {
    fontSize: 12,
    fontWeight: "800" as const,
    color: colors.paragraph,
  },
  pill: {
    minHeight: 34,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
  },
  pillLabel: {
    fontSize: 12,
    fontWeight: "700" as const,
    color: colors.paragraph,
  },
  pillStrong: {
    fontSize: 12,
    fontWeight: "900" as const,
    color: colors.headline,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 999,
  },
  modalBackdrop: {
    flex: 1,
    justifyContent: "flex-end" as const,
    backgroundColor: "rgba(0,0,0,0.35)",
  },
  sheet: {
    maxHeight: "82%",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    overflow: "hidden" as const,
  },
  sheetGrabber: {
    alignSelf: "center" as const,
    marginTop: 8,
    width: 44,
    height: 5,
    borderRadius: 999,
    backgroundColor: colors.border,
  },
  sheetHeader: {
    flexDirection: "row" as const,
    justifyContent: "space-between" as const,
    alignItems: "center" as const,
    gap: 10,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  sheetTitle: {
    fontSize: 16,
    fontWeight: "900" as const,
    color: colors.headline,
  },
  sheetCloseButton: {
    minHeight: 38,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  sheetCloseButtonText: {
    fontSize: 13,
    fontWeight: "800" as const,
    color: colors.headline,
  },
  sheetBody: {
    padding: 12,
    paddingBottom: 0,
    gap: 10,
  },
  searchInput: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    color: colors.paragraph,
    paddingHorizontal: 12,
    fontSize: 14,
  },
  iconGridScroll: {
    height: 360,
    flexGrow: 0,
  },
  iconGridScrollContent: {
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  iconGrid: {
    width: "100%",
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    marginHorizontal: -5,
  },
  iconTileCell: {
    width: "20%",
    paddingHorizontal: 5,
    paddingVertical: 5,
  },
  iconTile: {
    width: "100%",
    aspectRatio: 1,
    borderRadius: 14,
    paddingTop: 1,
    paddingBottom: 1,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  iconTileSelected: {
    borderWidth: 2,
    borderColor: colors.my_green,
    backgroundColor: colors.secondBackground,
  },
  iconTilePressed: {
    opacity: 0.8,
  },
  emptyStateText: {
    width: "100%",
    textAlign: "center" as const,
    color: colors.paragraph,
    paddingVertical: 14,
    fontSize: 14,
    fontWeight: "700" as const,
  },
  categoryRow: {
    flexDirection: "row" as const,
    flexWrap: "wrap" as const,
    gap: 8,
  },
  categoryButton: {
    minHeight: 34,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
    alignItems: "center" as const,
    justifyContent: "center" as const,
  },
  categoryButtonActive: {
    borderColor: colors.my_green,
    backgroundColor: colors.secondBackground,
  },
  categoryButtonText: {
    fontSize: 12,
    fontWeight: "800" as const,
    color: colors.paragraph,
  },
  categoryButtonTextActive: {
    color: colors.headline,
    fontWeight: "900" as const,
  },
  colorScroll: {
    flexGrow: 0,
  },
  colorScrollContent: {
    padding: 14,
    paddingBottom: 18,
    gap: 14,
  },
  colorActionRow: {
    flexDirection: "row" as const,
    alignItems: "center" as const,
    justifyContent: "flex-start" as const,
    gap: 8,
    marginTop: 2,
  },
  colorActionRight: {
    marginLeft: "auto" as const,
    flexDirection: "row" as const,
    alignItems: "center" as const,
    gap: 8,
  },
  colorFooterTextWrap: {
    minWidth: 78,
    flexShrink: 1,
  },
  colorPreviewLabel: {
    fontSize: 12,
    fontWeight: "900" as const,
    color: colors.paragraph,
  },
  colorPreviewHex: {
    marginTop: 2,
    fontSize: 13,
    fontWeight: "800" as const,
    color: colors.headline,
    fontVariant: ["tabular-nums"] as const,
  },
  colorPreviewBadge: {
    width: 46,
    height: 46,
    borderRadius: 16,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
  },
  closeSquareButton: {
    width: 32,
    height: 32,
    borderRadius: 4,
    alignItems: "center" as const,
    justifyContent: "center" as const,
    backgroundColor: colors.my_red,
    borderWidth: 1,
    borderColor: "rgba(255,255,255,0.1)",
  },
  closeSquareIcon: {
    color: colors.lightbg,
  },
  svPlaneWrap: {
    width: "100%",
    aspectRatio: 1.7,
    borderRadius: 18,
    overflow: "hidden" as const,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  svSvg: {
    width: "100%",
    height: "100%",
  },
  sliderGroup: {
    gap: 4,
  },
  sliderLabel: {
    fontSize: 12,
    fontWeight: "900" as const,
    color: colors.paragraph,
  },
  sliderControl: {
    width: "100%",
  },
  sliderTrack: {
    position: "relative" as const,
    width: "100%",
    height: 14,
    borderRadius: 999,
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "visible" as const,
  },
  hueTrack: {
    position: "relative" as const,
    width: "100%",
    height: 14,
    borderRadius: 999,
    backgroundColor: colors.secondBackground,
    borderWidth: 1,
    borderColor: colors.border,
    overflow: "visible" as const,
  },
  applyMyButton: {
    height: 44,
    minHeight: 44,
    borderRadius: 10,
    width: 126,
  },
  applyMyButtonText: {
    fontSize: 13,
    fontWeight: "900" as const,
  },
}));
