import { createThemeStylesHook } from "@/src/theme/createThemeStylesHook";

export const useStyles = createThemeStylesHook((colors) => ({
  container: {
    flex: 1,
    width: "100%",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    alignItems: "center",
  },
  heading: {
    fontSize: 34,
    fontWeight: "900",
    color: colors.headline,
    textAlign: "center",
  },
  subheading: {
    marginTop: 2,
    fontSize: 16,
    fontWeight: "400",
    color: colors.headline,
    textAlign: "center",
  },
  courseBadge: {
    marginTop: 18,
    width: "100%",
    minHeight: 40,
    paddingHorizontal: 4,
    paddingVertical: 0,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
  },
  courseBadgeStacked: {
    flexDirection: "column",
  },
  courseFlag: {
    width: 40*2,
    height: 28*2,
    borderRadius: 8,
  },
  customCourseIconWrapper: {
    alignItems: "center",
    justifyContent: "center",
    position: "relative",
    width: 60,
    height: 60,
  },
  customCourseMainImage: {
    width: 60,
    height: 60,
  },
  customCourseFlag: {
    position: "absolute",
    bottom: 0,
    right: -5,
    width: 99 / 3,
    height: 66 / 3,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.background,
  },
  courseName: {
    flexShrink: 1,
    maxWidth: "100%",
    fontSize: 22,
    fontWeight: "900",
    color: colors.headline,
    textAlign: "center",
  },
  logoWrap: {
    marginTop: 20,
    width: 220,
    height: 220,
    alignItems: "center",
    justifyContent: "center",
  },
  boxSkinWrap: {
    position: "relative",
    transform: [{ scale: 1.72 }],
  },
  boxShadow: {
    position: "absolute",
    width: 118,
    height: 28,
    left: -1,
    bottom: -6,
    zIndex: -1,
    opacity: 0.1,
  },
  statsHeading: {
    marginTop: 24,
    marginBottom: 8,
    fontSize: 18,
    fontWeight: "600",
    color: colors.headline,
    textAlign: "center",
  },
  statsRow: {
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  statsRowStacked: {
    flexDirection: "column",
  },
  statsCard: {
    flex: 1,
    minHeight: 132,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.secondBackground,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 10,
    paddingVertical: 16,
  },
  statsCardContent: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  statsIconWrap: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    marginBottom: 10,
  },
  statsValue: {
    fontSize: 24,
    fontWeight: "900",
    color: colors.headline,
    textAlign: "center",
  },
  statsLabel: {
    // marginTop: 3,
    fontSize: 14,
    fontWeight: "700",
    color: colors.paragraph,
    textAlign: "center",
  },
  actions: {
    width: "100%",
    marginTop: 28,
    gap: 12,
    alignItems: "center",
  },
}));
